# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0007_auto_20151223_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='target',
            field=models.IntegerField(choices=[(0, b'\xe5\x85\xa8\xe9\x83\xa8'), (1, b'\xe5\xaf\xb9\xe5\x9c\xb0\xe6\x94\xbb\xe5\x87\xbb'), (2, b'\xe5\xaf\xb9\xe7\xa9\xba\xe6\x94\xbb\xe5\x87\xbb')], default=0, verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\x9b\xae\xe6\xa0\x87'),
        ),
        migrations.AddField(
            model_name='unit',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\x9c\xb0\xe9\x9d\xa2\xe5\x8d\x95\xe4\xbd\x8d'), (2, b'\xe7\xa9\xba\xe4\xb8\xad\xe5\x8d\x95\xe4\xbd\x8d')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
