# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_auto_20160114_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='base_amount',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x95\xb0\xe9\x87\x8f'),
        ),
    ]
