# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0009_unit_base_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitEffect',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('effect', models.CharField(max_length=255)),
                ('race', models.IntegerField(choices=[(0, b'\xe5\x85\xa8\xe9\x83\xa8'), (1, b'\xe4\xba\xba\xe6\x97\x8f'), (2, b'\xe7\xa5\x9e\xe6\x97\x8f'), (3, b'\xe7\xa5\x9e\xe6\x97\x8f')], verbose_name=b'\xe7\xa7\x8d\xe6\x97\x8f')),
                ('tp', models.IntegerField(choices=[(1, b'\xe5\xaf\xb9\xe6\x92\x9e'), (2, b'\xe5\x8d\x95\xe6\x96\xb9\xe9\x9d\xa2\xe6\x8c\xa8\xe6\x89\x93'), (3, b'\xe6\xad\xbb\xe4\xba\xa1'), (4, b'\xe5\x87\xba\xe7\x94\x9f')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
            ],
            options={
                'db_table': 'unit_effect',
                'verbose_name': '\u5355\u4f4d\u7279\u6548',
                'verbose_name_plural': '\u5355\u4f4d\u7279\u6548',
            },
        ),
    ]
