# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0010_uniteffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteffect',
            name='race',
            field=models.IntegerField(choices=[(0, b'\xe5\x85\xa8\xe9\x83\xa8'), (1, b'\xe4\xba\xba\xe6\x97\x8f'), (2, b'\xe7\xa5\x9e\xe6\x97\x8f'), (3, b'\xe8\x99\xab\xe6\x97\x8f')], verbose_name=b'\xe7\xa7\x8d\xe6\x97\x8f'),
        ),
        migrations.AlterField(
            model_name='uniteffect',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\xaf\xb9\xe6\x92\x9e'), (2, b'\xe5\x8d\x95\xe6\x96\xb9\xe9\x9d\xa2\xe6\x8c\xa8\xe6\x89\x93'), (3, b'\xe6\xad\xbb\xe4\xba\xa1'), (4, b'\xe5\x87\xba\xe7\x94\x9f'), (5, b'\xe5\xa4\xa9\xe8\xb5\x8b')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
