# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0012_auto_20160202_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteffect',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\xaf\xb9\xe6\x92\x9e'), (2, b'\xe5\x8d\x95\xe6\x96\xb9\xe9\x9d\xa2\xe6\x8c\xa8\xe6\x89\x93'), (3, b'\xe6\xad\xbb\xe4\xba\xa1'), (4, b'\xe5\x87\xba\xe7\x94\x9f'), (5, b'\xe5\xa4\xa9\xe8\xb5\x8b'), (6, b'\xe5\xa4\xb1\xe8\xb4\xa5'), (7, b'\xe5\x91\x98\xe5\xb7\xa5\xe6\x8c\xa8\xe6\x89\x93')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
