# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_staffnew'),
        ('unit', '0013_auto_20160202_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97')),
                ('model', models.CharField(max_length=255, verbose_name=b'\xe6\xa8\xa1\xe5\x9e\x8b')),
                ('icon', models.CharField(max_length=255, verbose_name=b'\xe5\x9b\xbe\xe6\xa0\x87')),
                ('tp', models.IntegerField(choices=[(1, b'\xe5\x9c\xb0\xe9\x9d\xa2\xe5\x8d\x95\xe4\xbd\x8d'), (2, b'\xe7\xa9\xba\xe4\xb8\xad\xe5\x8d\x95\xe4\xbd\x8d')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('attack_tp', models.IntegerField(choices=[(1, b'\xe7\x89\xa9\xe7\x90\x86\xe6\x94\xbb\xe5\x87\xbb'), (2, b'\xe8\x83\xbd\xe9\x87\x8f\xe6\x94\xbb\xe5\x87\xbb')], verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('defense_tp', models.IntegerField(choices=[(1, b'\xe7\x94\x9f\xe7\x89\xa9\xe6\x8a\xa4\xe7\x94\xb2'), (2, b'\xe8\x83\xbd\xe9\x87\x8f\xe6\x8a\xa4\xe7\x94\xb2')], verbose_name=b'\xe9\x98\xb2\xe5\xbe\xa1\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('cost', models.IntegerField()),
                ('skill_1', models.IntegerField()),
                ('skill_2', models.IntegerField()),
                ('hp_max_base', models.IntegerField(verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x9c\x80\xe5\xa4\xa7\xe7\x94\x9f\xe5\x91\xbd\xe5\x80\xbc')),
                ('attack_base', models.IntegerField(verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x94\xbb\xe5\x87\xbb')),
                ('defense_base', models.IntegerField(verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe9\x98\xb2\xe5\xbe\xa1')),
                ('attack_speed_base', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x94\xbb\xe5\x87\xbb\xe9\x80\x9f\xe5\xba\xa6')),
                ('attack_range_base', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe6\x94\xbb\xe5\x87\xbb\xe5\xb0\x84\xe7\xa8\x8b')),
                ('move_speed_base', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x9f\xba\xe7\xa1\x80\xe7\xa7\xbb\xe5\x8a\xa8\xe9\x80\x9f\xe5\xba\xa6')),
                ('hit_rate', models.DecimalField(decimal_places=4, max_digits=4, verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87')),
                ('dodge_rate', models.DecimalField(decimal_places=4, max_digits=4, verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87')),
                ('crit_rate', models.DecimalField(decimal_places=4, max_digits=4, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87')),
                ('toughness_rate', models.DecimalField(decimal_places=4, max_digits=4, verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7')),
                ('hurt_addition_to_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('final_hurt_addition', models.IntegerField(verbose_name=b'\xe6\x9c\x80\xe7\xbb\x88\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('final_hurt_reduce', models.IntegerField(verbose_name=b'\xe6\x9c\x80\xe7\xbb\x88\xe4\xbc\xa4\xe5\xae\xb3\xe5\x87\x8f\xe5\x85\x8d')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffRace', verbose_name=b'\xe7\xa7\x8d\xe6\x97\x8f')),
            ],
            options={
                'db_table': 'unit_new',
                'verbose_name': '\u5175\u79cd\uff08\u65b0\uff09',
                'verbose_name_plural': '\u5175\u79cd\uff08\u65b0\uff09',
            },
        ),
    ]
