# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0017_auto_20160311_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnew',
            name='range_tp',
            field=models.IntegerField(choices=[(1, b'\xe8\xbf\x91\xe6\x88\x98'), (2, b'\xe8\xbf\x9c\xe7\xa8\x8b')], default=1, verbose_name=b'\xe8\x8c\x83\xe5\x9b\xb4\xe7\xb1\xbb\xe5\x9e\x8b'),
            preserve_default=False,
        ),
    ]
