# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0018_unitnew_range_tp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitnew',
            name='crit_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87'),
        ),
        migrations.AlterField(
            model_name='unitnew',
            name='dodge_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87'),
        ),
        migrations.AlterField(
            model_name='unitnew',
            name='hit_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87'),
        ),
        migrations.AlterField(
            model_name='unitnew',
            name='toughness_rate',
            field=models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7'),
        ),
    ]
