# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0019_auto_20160323_1518'),
    ]

    operations = [
        migrations.RenameField('UnitNew', 'cost', 'operation')
    ]
