# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0021_auto_20160329_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(db_index=True, verbose_name=b'\xe5\x85\xb5\xe7\xa7\x8dID')),
                ('unit_level', models.IntegerField(verbose_name=b'\xe7\xad\x89\xe7\xba\xa7')),
                ('update_item_need', models.CharField(blank=True, help_text=b'id,\xe6\x95\xb0\xe9\x87\x8f;id,\xe6\x95\xb0\xe9\x87\x8f...', max_length=255, verbose_name=b'\xe5\x8d\x87\xe5\x88\xb0\xe4\xb8\x8b\xe4\xb8\x80\xe7\xba\xa7\xe6\x89\x80\xe9\x9c\x80\xe9\x81\x93\xe5\x85\xb7')),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
            ],
            options={
                'db_table': 'unit_level',
                'verbose_name': '\u5175\u79cd\u5347\u7ea7',
                'verbose_name_plural': '\u5175\u79cd\u5347\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='UnitLevelAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('race', models.IntegerField()),
                ('level', models.IntegerField(verbose_name=b'\xe7\xad\x89\xe7\xba\xa7\xe6\x80\xbb\xe5\x92\x8c')),
                ('hp_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe7\x94\x9f\xe5\x91\xbd\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x98\xb2\xe5\xbe\xa1\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('hit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87')),
                ('dodge_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87')),
                ('crit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87')),
                ('toughness_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7')),
                ('crit_multiple', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe8\xa2\xab\xe7\x8e\x87')),
                ('hurt_addition_to_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
            ],
            options={
                'db_table': 'unit_level_addition',
                'verbose_name': '\u79cd\u65cf\u7b49\u7ea7\u52a0\u6210',
                'verbose_name_plural': '\u79cd\u65cf\u7b49\u7ea7\u52a0\u6210',
            },
        ),
        migrations.CreateModel(
            name='UnitStep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(db_index=True, verbose_name=b'\xe5\x85\xb5\xe7\xa7\x8dID')),
                ('unit_step', models.IntegerField(verbose_name=b'\xe9\x98\xb6')),
                ('level_limit', models.IntegerField(verbose_name=b'\xe7\xad\x89\xe7\xba\xa7\xe9\x99\x90\xe5\x88\xb6')),
                ('update_item_need', models.CharField(blank=True, help_text=b'id,\xe6\x95\xb0\xe9\x87\x8f;id,\xe6\x95\xb0\xe9\x87\x8f...', max_length=255, verbose_name=b'\xe5\x8d\x87\xe5\x88\xb0\xe4\xb8\x8b\xe4\xb8\x80\xe9\x98\xb6\xe6\x89\x80\xe9\x9c\x80\xe9\x81\x93\xe5\x85\xb7')),
                ('hp_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe7\x94\x9f\xe5\x91\xbd\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x98\xb2\xe5\xbe\xa1\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('hit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87')),
                ('dodge_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87')),
                ('crit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87')),
                ('toughness_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7')),
                ('crit_multiple', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe8\xa2\xab\xe7\x8e\x87')),
                ('hurt_addition_to_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
            ],
            options={
                'db_table': 'unit_step',
                'verbose_name': '\u5175\u79cd\u5347\u9636',
                'verbose_name_plural': '\u5175\u79cd\u5347\u9636',
            },
        ),
        migrations.CreateModel(
            name='UnitStepAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('race', models.IntegerField()),
                ('step', models.IntegerField(verbose_name=b'\xe7\xad\x89\xe7\xba\xa7\xe6\x80\xbb\xe5\x92\x8c')),
                ('hp_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe7\x94\x9f\xe5\x91\xbd\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x98\xb2\xe5\xbe\xa1\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('hit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87')),
                ('dodge_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87')),
                ('crit_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87')),
                ('toughness_rate', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7')),
                ('crit_multiple', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe8\xa2\xab\xe7\x8e\x87')),
                ('hurt_addition_to_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\xaf\xb9\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_terran', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_protoss', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_zerg', models.DecimalField(decimal_places=4, max_digits=8, verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
            ],
            options={
                'db_table': 'unit_step_addition',
                'verbose_name': '\u79cd\u65cf\u54c1\u9636\u52a0\u6210',
                'verbose_name_plural': '\u79cd\u65cf\u54c1\u9636\u52a0\u6210',
            },
        ),
        migrations.AddField(
            model_name='unitnew',
            name='unlock_club_level',
            field=models.IntegerField(default=0, verbose_name=b'\xe8\xa7\xa3\xe9\x94\x81\xe6\x89\x80\xe9\x9c\x80\xe4\xbf\xb1\xe4\xb9\x90\xe9\x83\xa8\xe7\xad\x89\xe7\xba\xa7'),
        ),
        migrations.AddField(
            model_name='unitnew',
            name='unlock_unit_level',
            field=models.CharField(blank=True, help_text=b'id,level;ld,level', max_length=255, verbose_name=b'\xe8\xa7\xa3\xe9\x94\x81\xe6\x89\x80\xe9\x9c\x80\xe5\x85\xb5\xe7\xa7\x8d\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
