# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0022_auto_20160406_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitUnLock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('need_club_level', models.IntegerField(default=0, verbose_name=b'\xe8\xa7\xa3\xe9\x94\x81\xe6\x89\x80\xe9\x9c\x80\xe4\xbf\xb1\xe4\xb9\x90\xe9\x83\xa8\xe7\xad\x89\xe7\xba\xa7')),
                ('need_unit_level', models.CharField(blank=True, help_text=b'id,level;ld,level', max_length=255, verbose_name=b'\xe8\xa7\xa3\xe9\x94\x81\xe6\x89\x80\xe9\x9c\x80\xe5\x85\xb5\xe7\xa7\x8d\xe7\xad\x89\xe7\xba\xa7')),
            ],
            options={
                'db_table': 'unit_unlock',
                'verbose_name': '\u5175\u79cd\u89e3\u9501',
                'verbose_name_plural': '\u5175\u79cd\u89e3\u9501',
            },
        ),
        migrations.RemoveField(
            model_name='unitnew',
            name='unlock_club_level',
        ),
        migrations.RemoveField(
            model_name='unitnew',
            name='unlock_unit_level',
        ),
    ]
