# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0026_auto_20160603_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnew',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
