# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0027_unitnew_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitnew',
            name='param_a',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unitnew',
            name='param_b',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='unitnew',
            name='param_c',
            field=models.FloatField(default=0),
        ),
    ]
