# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 08:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_staff_story_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='story_des',
        ),
    ]
