# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_remove_staff_story_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffquality',
            name='background_half',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x8d\x8a\xe8\xba\xab\xe5\x83\x8f'),
        ),
    ]
