# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_staffquality_background_half'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97')),
                ('picture', models.CharField(max_length=255, verbose_name=b'\xe5\x9b\xbe\xe7\x89\x87')),
                ('attack', models.IntegerField(verbose_name=b'\xe8\xbf\x9b\xe6\x94\xbb')),
                ('defense', models.IntegerField(verbose_name=b'\xe9\x98\xb2\xe5\xae\x88')),
                ('manage', models.IntegerField(verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5')),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'staff_new',
                'verbose_name': '\u9009\u624b\uff08\u65b0\uff09',
                'verbose_name_plural': '\u9009\u624b\uff08\u65b0\uff09',
            },
        ),
    ]
