# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_staffnew'),
    ]

    operations = [
        migrations.RenameField('StaffNew', 'cost', 'operation')
    ]
