# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20160329_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffLevelNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe7\xad\x89\xe7\xba\xa7')),
                ('exp', models.IntegerField(verbose_name=b'\xe6\x89\x80\xe9\x9c\x80\xe7\xbb\x8f\xe9\xaa\x8c')),
            ],
            options={
                'db_table': 'staff_level_new',
                'verbose_name': '\u9009\u624b\u7b49\u7ea7\uff08\u65b0\uff09',
                'verbose_name_plural': '\u9009\u624b\u7b49\u7ea7\uff08\u65b0\uff09',
            },
        ),
        migrations.CreateModel(
            name='StaffStar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7')),
                ('exp', models.IntegerField(verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe7\xbb\x8f\xe9\xaa\x8c')),
                ('need_item_id', models.IntegerField()),
                ('need_item_amount', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defense', models.IntegerField()),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('manage', models.IntegerField()),
                ('manage_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('operation', models.IntegerField()),
                ('operation_percent', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'db_table': 'staff_star',
                'verbose_name': '\u9009\u624b\u5347\u661f\uff08\u65b0\uff09',
                'verbose_name_plural': '\u9009\u624b\u5347\u661f\uff08\u65b0\uff09',
            },
        ),
        migrations.CreateModel(
            name='StaffStep',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField(db_index=True, verbose_name=b'\xe9\x80\x89\xe6\x89\x8bID')),
                ('staff_step', models.IntegerField(verbose_name=b'\xe9\x98\xb6')),
                ('attack', models.IntegerField()),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defense', models.IntegerField()),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('manage', models.IntegerField()),
                ('manage_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('operation', models.IntegerField()),
                ('operation_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('talent_skill', models.IntegerField()),
                ('update_item_need', models.CharField(blank=True, help_text=b'id,\xe6\x95\xb0\xe9\x87\x8f;id,\xe6\x95\xb0\xe9\x87\x8f...', max_length=255, verbose_name=b'\xe5\x8d\x87\xe5\x88\xb0\xe6\x9c\xac\xe9\x98\xb6\xe6\x89\x80\xe9\x9c\x80\xe9\x81\x93\xe5\x85\xb7')),
                ('level_limit', models.IntegerField(verbose_name=b'\xe9\x80\x89\xe6\x89\x8b\xe7\xad\x89\xe7\xba\xa7\xe9\x99\x90\xe5\x88\xb6')),
            ],
            options={
                'db_table': 'staff_step',
                'verbose_name': '\u9009\u624b\u5347\u9636\uff08\u65b0\uff09',
                'verbose_name_plural': '\u9009\u624b\u5347\u9636\uff08\u65b0\uff09',
            },
        ),
        migrations.AddField(
            model_name='staffnew',
            name='attack_grow',
            field=models.IntegerField(default=1, verbose_name=b'\xe8\xbf\x9b\xe6\x94\xbb\xe5\xa2\x9e\xe9\x95\xbf'),
        ),
        migrations.AddField(
            model_name='staffnew',
            name='crystal',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x88\x86\xe8\xa7\xa3\xe8\x8e\xb7\xe5\xbe\x97\xe6\xb0\xb4\xe6\x99\xb6'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffnew',
            name='defense_grow',
            field=models.IntegerField(default=1, verbose_name=b'\xe9\x98\xb2\xe5\xae\x88\xe5\xa2\x9e\xe9\x95\xbf'),
        ),
        migrations.AddField(
            model_name='staffnew',
            name='manage_grow',
            field=models.IntegerField(default=1, verbose_name=b'\xe8\xbf\x90\xe8\x90\xa5\xe5\xa2\x9e\xe9\x95\xbf'),
        ),
        migrations.AddField(
            model_name='staffnew',
            name='operation_grow',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe5\xa2\x9e\xe9\x95\xbf'),
        ),
        migrations.AddField(
            model_name='staffnew',
            name='race',
            field=models.IntegerField(default=1, verbose_name=b'\xe7\xa7\x8d\xe6\x97\x8f'),
        ),
        migrations.AddField(
            model_name='staffnew',
            name='skill',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x8a\x80\xe8\x83\xbdID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffnew',
            name='talent_skill',
            field=models.CommaSeparatedIntegerField(default='', help_text=b'id,id,id', max_length=255, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8bID'),
            preserve_default=False,
        ),
    ]
