# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20160329_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafflevelnew',
            name='exp',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x89\x80\xe9\x9c\x80\xe7\xbb\x8f\xe9\xaa\x8c'),
        ),
        migrations.AlterField(
            model_name='staffstar',
            name='exp',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe7\xbb\x8f\xe9\xaa\x8c'),
        ),
        migrations.AlterField(
            model_name='staffstar',
            name='need_item_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffstar',
            name='need_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staffstep',
            name='level_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'\xe9\x80\x89\xe6\x89\x8b\xe7\xad\x89\xe7\xba\xa7\xe9\x99\x90\xe5\x88\xb6'),
        ),
    ]
