# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20160329_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafflevelnew',
            options={'ordering': ('id',), 'verbose_name': '\u9009\u624b\u7b49\u7ea7\uff08\u65b0\uff09', 'verbose_name_plural': '\u9009\u624b\u7b49\u7ea7\uff08\u65b0\uff09'},
        ),
        migrations.AlterModelOptions(
            name='staffstar',
            options={'ordering': ('id',), 'verbose_name': '\u9009\u624b\u5347\u661f\uff08\u65b0\uff09', 'verbose_name_plural': '\u9009\u624b\u5347\u661f\uff08\u65b0\uff09'},
        ),
        migrations.AlterModelOptions(
            name='staffstep',
            options={'ordering': ('id',), 'verbose_name': '\u9009\u624b\u5347\u9636\uff08\u65b0\uff09', 'verbose_name_plural': '\u9009\u624b\u5347\u9636\uff08\u65b0\uff09'},
        ),
    ]
