# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0029_auto_20160406_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEquipmentLevelAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField(blank=True, verbose_name=b'\xe8\xaf\xb4\xe6\x98\x8e')),
                ('attack', models.IntegerField()),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defense', models.IntegerField()),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('manage', models.IntegerField()),
                ('manage_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('operation', models.IntegerField()),
                ('operation_percent', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'staff_equipment_level_addition',
                'verbose_name': '\u88c5\u5907\u7b49\u7ea7\u5956\u52b1',
                'verbose_name_plural': '\u88c5\u5907\u7b49\u7ea7\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='StaffEquipmentQualityAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField(blank=True, verbose_name=b'\xe8\xaf\xb4\xe6\x98\x8e')),
                ('attack', models.IntegerField()),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defense', models.IntegerField()),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('manage', models.IntegerField()),
                ('manage_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('operation', models.IntegerField()),
                ('operation_percent', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
            options={
                'ordering': ('id',),
                'db_table': 'staff_equipment_quality_addition',
                'verbose_name': '\u88c5\u5907\u54c1\u8d28\u5956\u52b1',
                'verbose_name_plural': '\u88c5\u5907\u54c1\u8d28\u5956\u52b1',
            },
        ),
    ]
