# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0032_auto_20160411_1637'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffHot',
        ),
        migrations.RemoveField(
            model_name='staffrecruitsettings',
            name='recruit',
        ),
        migrations.DeleteModel(
            name='StaffRecruit',
        ),
        migrations.DeleteModel(
            name='StaffRecruitSettings',
        ),
    ]
