# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-18 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0033_auto_20160418_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRecruit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField(choices=[(1, b'\xe6\x99\xae\xe9\x80\x9a\xe6\x8a\xbd\xe5\x8d\xa1'), (2, b'\xe9\x92\xbb\xe7\x9f\xb3\xe6\x8a\xbd\xe5\x8d\xa1')])),
                ('min_point', models.IntegerField(verbose_name=b'\xe6\x9c\x80\xe5\xb0\x8f\xe7\x82\xb9\xe6\x95\xb0')),
                ('items', models.CharField(help_text=b'id,\xe5\x87\xa0\xe7\x8e\x87;id,\xe5\x87\xa0\xe7\x8e\x87... \xe5\x87\xa0\xe7\x8e\x87\xe5\x9f\xba\xe6\x95\xb0\xe6\x98\xaf\xe4\xb8\x80\xe4\xb8\x87', max_length=255)),
            ],
            options={
                'db_table': 'staff_recruit',
                'verbose_name': '\u62bd\u5361',
                'verbose_name_plural': '\u62bd\u5361',
            },
        ),
        migrations.CreateModel(
            name='StaffRecruitSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost_type', models.IntegerField(choices=[(1, b'\xe9\x87\x91\xe5\xb8\x81'), (2, b'\xe9\x92\xbb\xe7\x9f\xb3')])),
                ('cost_value_1', models.IntegerField(verbose_name=b'\xe5\x8d\x95\xe6\xac\xa1\xe8\x8a\xb1\xe8\xb4\xb9')),
                ('cost_value_10', models.IntegerField(verbose_name=b'10\xe8\xbf\x9e\xe6\x8a\xbd\xe8\x8a\xb1\xe8\xb4\xb9')),
                ('items_10', models.CharField(max_length=255, verbose_name=b'\xe7\xac\xac10\xe6\xac\xa1\xe4\xba\xa7\xe5\x87\xba')),
                ('reward_score_times', models.IntegerField(verbose_name=b'\xe8\x8e\xb7\xe5\x8f\x96\xe7\xa7\xaf\xe5\x88\x86\xe7\x9a\x84\xe6\x8a\xbd\xe5\x8d\xa1\xe6\xac\xa1\xe6\x95\xb0')),
                ('reward_score', models.IntegerField(verbose_name=b'\xe7\xa7\xaf\xe5\x88\x86')),
                ('reward_score_day_limit', models.IntegerField(help_text=b'0\xe8\xa1\xa8\xe7\xa4\xba\xe6\xb2\xa1\xe6\x9c\x89\xe4\xb8\x8a\xe9\x99\x90', verbose_name=b'\xe6\xaf\x8f\xe5\xa4\xa9\xe8\x8e\xb7\xe5\xbe\x97\xe7\xa7\xaf\xe5\x88\x86\xe4\xb8\x8a\xe9\x99\x90')),
            ],
            options={
                'db_table': 'staff_recruit_settings',
                'verbose_name': '\u62bd\u5361\u57fa\u672c\u8bbe\u7f6e',
                'verbose_name_plural': '\u62bd\u5361\u57fa\u672c\u8bbe\u7f6e',
            },
        ),
    ]
