# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0034_staffrecruit_staffrecruitsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecruitsettings',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
