# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_staffrecruitsettings_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruit',
            name='items',
            field=models.TextField(help_text=b'id,\xe5\x87\xa0\xe7\x8e\x87;id,\xe5\x87\xa0\xe7\x8e\x87... \xe5\x87\xa0\xe7\x8e\x87\xe5\x9f\xba\xe6\x95\xb0\xe6\x98\xaf\xe4\xb8\x80\xe4\xb8\x87'),
        ),
        migrations.AlterField(
            model_name='staffrecruitsettings',
            name='items_10',
            field=models.TextField(verbose_name=b'\xe7\xac\xac10\xe6\xac\xa1\xe4\xba\xa7\xe5\x87\xba'),
        ),
    ]
