# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_auto_20160421_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnew',
            name='talent_skill',
            field=models.CommaSeparatedIntegerField(blank=True, help_text=b'id,id,id', max_length=255, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8bID'),
        ),
    ]
