# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_auto_20160421_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrecruitsettings',
            name='items_1',
            field=models.TextField(default='', verbose_name=b'\xe7\xac\xac1\xe6\xac\xa1\xe4\xba\xa7\xe5\x87\xba'),
            preserve_default=False,
        ),
    ]
