# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0038_staffrecruitsettings_items_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffrecruit',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe6\x99\xae\xe9\x80\x9a\xe6\x8a\xbd\xe5\x8d\xa1'), (2, b'\xe9\x92\xbb\xe7\x9f\xb3\xe6\x8a\xbd\xe5\x8d\xa1'), (3, b'\xe9\x92\xbb\xe7\x9f\xb3\xe5\x85\x8d\xe8\xb4\xb9\xe6\x8a\xbd\xe5\x8d\xa1')]),
        ),
    ]
