# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_auto_20160615_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrace',
            name='effect',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffrace',
            name='show_delay',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='staffrace',
            name='show_mode',
            field=models.IntegerField(default=1),
        ),
    ]
