# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('building_id', models.IntegerField()),
                ('building_level', models.IntegerField()),
                ('exp', models.IntegerField()),
                ('max_times', models.IntegerField()),
                ('reward', models.TextField(help_text='id,amount,prob;  \u6982\u7387\u548c\u4e3a100')),
            ],
            options={
                'db_table': 'territory_inspire',
                'verbose_name': '\u9f13\u821e',
                'verbose_name_plural': '\u9f13\u821e',
            },
        ),
        migrations.AddField(
            model_name='staffspecialproduct',
            name='des_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffspecialproduct',
            name='des_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffspecialproduct',
            name='des_3',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='inspire',
            unique_together=set([('building_id', 'building_level')]),
        ),
    ]
