# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0002_auto_20160516_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspireCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diamond', models.IntegerField()),
            ],
            options={
                'db_table': 'territory_inspire_cost',
                'verbose_name': '\u9f13\u821e\u82b1\u8d39',
                'verbose_name_plural': '\u9f13\u821e\u82b1\u8d39',
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('used_for', models.CharField(max_length=255, verbose_name='\u7528\u4e8e')),
                ('template', models.TextField()),
            ],
            options={
                'db_table': 'territory_report_template',
                'verbose_name': '\u5de5\u4f5c\u62a5\u544a\u6a21\u677f',
                'verbose_name_plural': '\u5de5\u4f5c\u62a5\u544a\u6a21\u677f',
            },
        ),
    ]
