# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0004_remove_territorybuilding_building_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingslotextraproduct',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
