# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0005_buildingslotextraproduct_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerritoryStore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField(choices=[(1, '\u666e\u901a\u5151\u6362'), (2, '\u9ad8\u7ea7\u5151\u6362')])),
                ('item_id', models.IntegerField()),
                ('item_amount', models.IntegerField()),
                ('sequence', models.IntegerField(verbose_name='\u4f4d\u7f6e')),
                ('needs', models.TextField(verbose_name='\u6240\u9700\u8d44\u6e90')),
                ('condition_id', models.IntegerField(choices=[(-1, 'VIP\u7b49\u7ea7'), (101, '\u5efa\u7b51\u7b49\u7ea7101'), (102, '\u5efa\u7b51\u7b49\u7ea7102'), (103, '\u5efa\u7b51\u7b49\u7ea7103')], verbose_name='\u6761\u4ef6ID')),
                ('condition_value', models.IntegerField(default=0, verbose_name='\u6761\u4ef6\u503c')),
                ('max_times', models.IntegerField(verbose_name='\u6b21\u6570\u9650\u5236')),
            ],
            options={
                'db_table': 'territory_store',
                'verbose_name': '\u5546\u5e97',
                'verbose_name_plural': '\u5546\u5e97',
            },
        ),
    ]
