# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0007_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='resource',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
