# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBuy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('items', models.TextField()),
                ('diamond_original', models.IntegerField()),
                ('diamond_now', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_buy',
                'verbose_name': '\u6bcf\u65e5\u8d2d\u4e70',
                'verbose_name_plural': '\u6bcf\u65e5\u8d2d\u4e70',
            },
        ),
        migrations.CreateModel(
            name='NewPlayerActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('condition_id', models.IntegerField()),
                ('condition_param', models.IntegerField()),
                ('condition_value', models.IntegerField()),
                ('rewards', models.TextField()),
                ('show_progress', models.BooleanField()),
            ],
            options={
                'db_table': 'activity_new_player',
                'verbose_name': '\u65b0\u624b\u6d3b\u52a8',
                'verbose_name_plural': '\u65b0\u624b\u6d3b\u52a8',
            },
        ),
    ]
