# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_remove_newplayeractivity_condition_param'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField()),
                ('rewards', models.TextField()),
            ],
            options={
                'db_table': 'activity_challenge',
                'verbose_name': '\u51b2\u5173\u6d3b\u52a8',
                'verbose_name_plural': '\u51b2\u5173\u6d3b\u52a8',
            },
        ),
        migrations.CreateModel(
            name='OnlineTimeActivity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('online_time', models.IntegerField()),
                ('des', models.TextField()),
                ('rewards', models.TextField()),
            ],
            options={
                'db_table': 'online_time_activity',
                'verbose_name': '\u5728\u7ebf\u65f6\u957f\u6d3b\u52a8',
                'verbose_name_plural': '\u5728\u7ebf\u65f6\u957f\u6d3b\u52a8',
            },
        ),
    ]
