# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_challengeactivity_onlinetimeactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeactivity',
            name='des',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='onlinetimeactivity',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
