# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'first_name',
                'verbose_name': '\u59d3',
                'verbose_name_plural': '\u59d3',
            },
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'last_name',
                'verbose_name': '\u540d',
                'verbose_name_plural': '\u540d',
            },
        ),
    ]
