# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_auto_20151230_1453'),
        ('league', '0003_league_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='day_reward',
        ),
        migrations.RemoveField(
            model_name='league',
            name='day_reward_lose',
        ),
        migrations.RemoveField(
            model_name='league',
            name='week_reward',
        ),
        migrations.AddField(
            model_name='league',
            name='daily_reward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='league_daily_reward', to='package.Package', verbose_name=b'\xe6\xaf\x8f\xe6\x97\xa5\xe5\xa5\x96\xe5\x8a\xb1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='up_need_score',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x99\x8b\xe7\xba\xa7\xe7\xa7\xaf\xe5\x88\x86'),
            preserve_default=False,
        ),
    ]
