# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20151230_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='icon_path',
            field=models.CharField(default='ss', max_length=255, verbose_name=b'\xe7\xad\x89\xe7\xba\xa7\xe5\x9b\xbe\xe6\xa0\x87'),
            preserve_default=False,
        ),
    ]
