# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='need_challenge_id',
            field=models.IntegerField(default=0, verbose_name=b'\xe6\x89\x80\xe9\x9c\x80\xe5\x85\xb3\xe5\x8d\xa1ID'),
        ),
    ]
