# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:05
from __future__ import unicode_literals

from django.db import migrations, connection

def drop_index(apps, scheme_editor):
    cursor = connection.cursor()
    cursor.execute("select INDEX_NAME from information_schema.STATISTICS where TABLE_NAME = 'function' and COLUMN_NAME='belong_to_building_id';")
    res = cursor.fetchone()
    index_name = res[0]
    cursor.execute("drop index {0} on function".format(index_name))

    cursor.close()


def change_null_to_0(apps, scheme_editor):
    Model = apps.get_model("function", "Function")
    Model.objects.filter(belong_to_building=None).update(belong_to_building=0)


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0002_function_need_challenge_id'),
    ]

    operations = [
        migrations.RunPython(drop_index),
        migrations.RunPython(change_null_to_0)
    ]
