# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_auto_20160512_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='belong_to_building',
            field=models.IntegerField(verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe5\xbb\xba\xe7\xad\x91'),
        ),
    ]
