# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_auto_20160512_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='belong_to_ui',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
