# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_function_belong_to_ui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='function',
            name='need_building_level',
        ),
        migrations.AddField(
            model_name='function',
            name='need_club_level',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\x89\x80\xe9\x9c\x80\xe4\xbf\xb1\xe4\xb9\x90\xe9\x83\xa8\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
