# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0006_auto_20160512_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='lock_color',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='function',
            name='normal_color',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
