# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField(verbose_name='\u7c7b\u578b')),
                ('tp_name', models.CharField(max_length=255)),
                ('club_level_min', models.IntegerField(default=0, help_text='0 \u8868\u793a\u6ca1\u6709\u9650\u5236')),
                ('club_level_max', models.IntegerField(default=0, help_text='0 \u8868\u793a\u6ca1\u6709\u9650\u5236')),
                ('money_id', models.IntegerField(verbose_name='\u663e\u793a\u7684\u8d27\u5e01')),
                ('refresh_hour_interval', models.IntegerField(verbose_name='\u81ea\u52a8\u5237\u65b0\u95f4\u9694\u5c0f\u65f6\u6570')),
                ('position', models.IntegerField(verbose_name='\u4f4d\u7f6e')),
                ('condition_id', models.IntegerField()),
                ('condition_value', models.IntegerField()),
                ('times_limit', models.IntegerField()),
                ('content', models.TextField(help_text='\u552e\u5356ID,\u552e\u5356\u6570\u91cf;\u9700\u8981ID,\u9700\u8981\u6570\u91cf')),
            ],
            options={
                'db_table': 'store',
                'verbose_name': '\u5546\u5e97',
                'verbose_name_plural': '\u5546\u5e97',
            },
        ),
        migrations.CreateModel(
            name='StoreCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'store_condition',
                'verbose_name': '\u5546\u5e97\u6761\u4ef6',
                'verbose_name_plural': '\u5546\u5e97\u6761\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='StoreRefresh',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('store_tp', models.IntegerField(verbose_name='\u5546\u5e97\u7c7b\u578b')),
                ('times', models.IntegerField(verbose_name='\u5237\u65b0\u6b21\u6570')),
                ('diamond', models.IntegerField(verbose_name='\u6240\u9700\u94bb\u77f3')),
            ],
            options={
                'db_table': 'store_refresh',
                'verbose_name': '\u5237\u65b0\u82b1\u8d39',
                'verbose_name_plural': '\u5237\u65b0\u82b1\u8d39',
            },
        ),
    ]
