# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('money_id', models.IntegerField()),
                ('refresh_hour_interval', models.IntegerField(verbose_name='\u81ea\u52a8\u5237\u65b0\u95f4\u9694\u5c0f\u65f6\u6570')),
            ],
            options={
                'db_table': 'store_type',
                'verbose_name': '\u5546\u5e97\u7c7b\u578b',
                'verbose_name_plural': '\u5546\u5e97\u7c7b\u578b',
            },
        ),
        migrations.RemoveField(
            model_name='store',
            name='money_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='refresh_hour_interval',
        ),
        migrations.RemoveField(
            model_name='store',
            name='tp_name',
        ),
    ]
