# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-27 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'background_image',
                'verbose_name': '\u80cc\u666f\u56fe\u7247',
                'verbose_name_plural': '\u80cc\u666f\u56fe\u7247',
            },
        ),
    ]
