# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20151104_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
                ('mean', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'global_config',
            },
        ),
    ]
