# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_globalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
