# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_delete_trainingskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingproperty',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\xb1\x9e\xe6\x80\xa7\xe8\xae\xad\xe7\xbb\x83'), (2, b'\xe7\xbb\x8f\xe9\xaa\x8c\xe8\xae\xad\xe7\xbb\x83')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
