# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_auto_20151110_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='package',
        ),
        migrations.AddField(
            model_name='guide',
            name='after_dialog',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='after_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='after_position',
            field=models.IntegerField(choices=[(1, b'\xe5\xb7\xa6'), (2, b'\xe5\x8f\xb3')], default=1),
        ),
        migrations.AddField(
            model_name='guide',
            name='before_dialog',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='before_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='before_position',
            field=models.IntegerField(choices=[(1, b'\xe5\xb7\xa6'), (2, b'\xe5\x8f\xb3')], default=1),
        ),
    ]
