# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 02:32
from __future__ import unicode_literals

from django.db import migrations


def set_new_fields(apps, schema_editor):
    Guide = apps.get_module('guide', 'Guide')
    for g in Guide.objects.all():
        before_dialog = g.dialog_before.first()
        if before_dialog:
            g.before_icon = before_dialog.icon
            g.before_position = before_dialog.position
            g.before_dialog = before_dialog.dialog

        after_dialog = g.dialog_after.first()
        if after_dialog:
            g.before_icon = after_dialog.icon
            g.before_position = after_dialog.position
            g.after_dialog = after_dialog.dialog

        g.save()

class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20160524_1032'),
    ]

    operations = [
        migrations.RunPython(set_new_fields)
    ]
