# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_auto_20160620_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='operate_type',
            field=models.IntegerField(choices=[(0, b'\xe7\xa9\xba\xe6\x93\x8d\xe4\xbd\x9c'), (1, b'\xe7\x82\xb9\xe5\x87\xbbUI'), (2, b'\xe6\x8b\x96\xe5\x8a\xa8UI'), (3, b'\xe7\x82\xb9\xe5\x87\xbb\xe5\xbb\xba\xe7\xad\x91'), (4, b'\xe6\x8b\x96\xe5\x8a\xa8\xe9\x98\xb5\xe5\x9e\x8b'), (5, b'\xe4\xb8\x8a\xe9\x98\xb5')], verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
