# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_auto_20160622_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='delay',
            field=models.IntegerField(default=0),
        ),
    ]
