# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0020_auto_20151113_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMain',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('next_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('challenge_id', models.IntegerField()),
                ('items', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'task_main',
                'verbose_name': '\u4e3b\u7ebf\u4efb\u52a1',
                'verbose_name_plural': '\u4e3b\u7ebf\u4efb\u52a1',
            },
        ),
    ]
