# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-05 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0021_taskmain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmain',
            name='next_id',
        ),
    ]
