# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0022_remove_taskmain_next_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCondition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ui', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'task_condition',
                'verbose_name': '\u4efb\u52a1\u6761\u4ef6',
                'verbose_name_plural': '\u4efb\u52a1\u6761\u4ef6',
            },
        ),
        migrations.CreateModel(
            name='TaskDaily',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('club_level', models.IntegerField()),
                ('vip_level', models.IntegerField()),
                ('condition_id', models.IntegerField()),
                ('condition_value', models.IntegerField()),
                ('rewards', models.TextField(help_text=b'id,amount;id,amount;...')),
            ],
            options={
                'db_table': 'task_daily',
                'verbose_name': '\u65e5\u5e38\u4efb\u52a1',
                'verbose_name_plural': '\u65e5\u5e38\u4efb\u52a1',
            },
        ),
        migrations.RemoveField(
            model_name='task',
            name='reward',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tp',
        ),
        migrations.RemoveField(
            model_name='task',
            name='trigger',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.RemoveField(
            model_name='tasktarget',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasktarget',
            name='tp',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskTarget',
        ),
        migrations.DeleteModel(
            name='TaskTargetType',
        ),
        migrations.DeleteModel(
            name='TaskTrigger',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
