# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_auto_20160526_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='server_module',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
