# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_taskcondition_server_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcondition',
            name='ui',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
