# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0025_auto_20160531_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='scene',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
