# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0026_taskcondition_scene'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomevent',
            name='package',
        ),
        migrations.RemoveField(
            model_name='randomeventdialogafter',
            name='random_event',
        ),
        migrations.RemoveField(
            model_name='randomeventdialogbefore',
            name='random_event',
        ),
        migrations.DeleteModel(
            name='RandomEvent',
        ),
        migrations.DeleteModel(
            name='RandomEventDialogAfter',
        ),
        migrations.DeleteModel(
            name='RandomEventDialogBefore',
        ),
    ]
