# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0027_auto_20160706_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='param',
            field=models.IntegerField(default=0),
        ),
    ]
