# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0028_taskcondition_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='time_limit',
            field=models.BooleanField(default=False),
        ),
    ]
