# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0029_taskcondition_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcondition',
            name='compare_type',
            field=models.CharField(default=b'>=', max_length=32),
        ),
    ]
