# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0030_taskcondition_compare_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdaily',
            name='challenge_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
