# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(verbose_name='\u51fa\u552e\u65f6\u957f')),
                ('tax', models.IntegerField(verbose_name='\u51fa\u552e\u7a0e\u7387')),
            ],
            options={
                'db_table': 'auction',
                'verbose_name': '\u62cd\u5356',
                'verbose_name_plural': '\u62cd\u5356',
            },
        ),
    ]
