# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='des',
            field=models.CharField(default='', max_length=255, verbose_name='\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
