# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartyBuyItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('reward', models.TextField()),
            ],
            options={
                'db_table': 'party_buy_item',
                'verbose_name': '\u5bb4\u4f1a\u8d2d\u4e70',
                'verbose_name_plural': '\u5bb4\u4f1a\u8d2d\u4e70',
            },
        ),
        migrations.CreateModel(
            name='PartyLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('need_union_level', models.IntegerField()),
                ('need_diamond', models.IntegerField()),
                ('talent_skills', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('mail_title', models.TextField()),
                ('mail_content', models.TextField()),
                ('buy_one', models.IntegerField()),
                ('buy_two', models.IntegerField()),
            ],
            options={
                'db_table': 'party_level',
                'verbose_name': '\u5bb4\u4f1a\u7b49\u7ea7',
                'verbose_name_plural': '\u5bb4\u4f1a\u7b49\u7ea7',
            },
        ),
    ]
