# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5c42\u7ea7ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u5c42\u7ea7\u540d')),
                ('buff', models.IntegerField(verbose_name='\u526f\u672c\u6548\u679c')),
                ('npc_path', models.CharField(help_text='\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID;\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID(\u4f4d\u7f6e\u8303\u56f40~29)', max_length=255, verbose_name='npc\u914d\u7f6e')),
                ('star_one', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='1\u661f\u5956\u52b1')),
                ('star_two', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='2\u661f\u5956\u52b1')),
                ('star_three', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='3\u661f\u5956\u52b1')),
                ('sale_goods', models.CharField(blank=True, help_text='\u6298\u6263\u5546\u54c1ID,\u6298\u6263\u5546\u54c1...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=255, verbose_name='\u6298\u6263\u5546\u54c1')),
                ('roulette_three', models.CharField(blank=True, help_text='\u5929\u8d4bID,\u5929\u8d4bID...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='3\u661f\u5929\u8d4b')),
                ('roulette_six', models.CharField(blank=True, help_text='\u5929\u8d4bID,\u5929\u8d4bID...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='6\u661f\u5929\u8d4b')),
                ('roulette_nine', models.CharField(blank=True, help_text='\u5929\u8d4bID,\u5929\u8d4bID...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='9\u661f\u5929\u8d4b')),
            ],
            options={
                'db_table': 'tower_level',
                'verbose_name': '\u5c42\u7ea7',
                'verbose_name_plural': '\u5c42\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='RankReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u722c\u5854\u5956\u52b1ID')),
                ('rank_cap', models.IntegerField(verbose_name='\u6392\u540d\u533a\u95f4\u4e0a\u9650')),
                ('rank_floor', models.IntegerField(verbose_name='\u6392\u540d\u533a\u95f4\u4e0b\u9650')),
                ('reward', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf', max_length=255, verbose_name='\u6392\u540d\u5956\u52b1')),
                ('mail_sender', models.CharField(max_length=32, verbose_name='\u90ae\u4ef6ID')),
            ],
            options={
                'db_table': 'tower_rank_reward',
                'verbose_name': '\u722c\u5854\u5956\u52b1',
                'verbose_name_plural': '\u722c\u5854\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='SaleGoods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5546\u54c1ID')),
                ('item', models.IntegerField(verbose_name='\u7269\u54c1ID')),
                ('tp', models.IntegerField(verbose_name='\u7269\u54c1\u7c7b\u522b')),
                ('tp_icon', models.CharField(max_length=255, verbose_name='\u7c7b\u522bicon')),
                ('price', models.IntegerField(verbose_name='\u5546\u54c1\u4ef7\u683c')),
                ('sale', models.IntegerField(blank=True, help_text='\u975e\u4fc3\u9500\u5546\u54c1\u4e0d\u586b', verbose_name='\u4fc3\u9500\u4ef7')),
                ('vip_need', models.IntegerField(blank=True, help_text='\u975e\u4fc3\u9500\u5546\u54c1\u4e0d\u586b', verbose_name='\u4fc3\u9500\u4ef7\u6240\u9700vip\u7b49\u7ea7')),
                ('num', models.IntegerField(verbose_name='\u4fc3\u9500\u6570\u91cf')),
                ('des', models.CharField(blank=True, max_length=255, verbose_name='\u4fc3\u9500\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'tower_sale_goods',
                'verbose_name': '\u4fc3\u9500\u5546\u54c1',
                'verbose_name_plural': '\u4fc3\u9500\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='StarReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u661f\u7ea7\u5956\u52b1')),
                ('star', models.IntegerField(verbose_name='\u6240\u9700\u661f\u6570')),
                ('reward', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf', max_length=255, verbose_name='\u661f\u7ea7\u5956\u52b1')),
            ],
            options={
                'db_table': 'tower_star_reward',
                'verbose_name': '\u661f\u7ea7\u5956\u52b1',
                'verbose_name_plural': '\u661f\u7ea7\u5956\u52b1',
            },
        ),
    ]
