# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowerResetCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u722c\u5854\u91cd\u7f6eID')),
                ('times', models.IntegerField(verbose_name='\u7b2c\u51e0\u6b21\u8d2d\u4e70')),
                ('cost', models.IntegerField(verbose_name='\u6d88\u8017\u94bb\u77f3')),
            ],
            options={
                'db_table': 'tower_reset_cost',
                'verbose_name': '\u91cd\u7f6e\u6d88\u8017',
                'verbose_name_plural': '\u91cd\u7f6e\u6d88\u8017',
            },
        ),
        migrations.RenameModel(
            old_name='GameLevel',
            new_name='TowerGameLevel',
        ),
        migrations.RenameModel(
            old_name='RankReward',
            new_name='TowerRankReward',
        ),
        migrations.RenameModel(
            old_name='SaleGoods',
            new_name='TowerSaleGoods',
        ),
        migrations.RenameModel(
            old_name='StarReward',
            new_name='TowerStarReward',
        ),
    ]
