# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0002_auto_20160429_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towergamelevel',
            name='roulette_nine',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,\u6982\u7387;...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='9\u661f\u5929\u8d4b'),
        ),
        migrations.AlterField(
            model_name='towergamelevel',
            name='roulette_six',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,\u6982\u7387;...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='6\u661f\u5929\u8d4b'),
        ),
        migrations.AlterField(
            model_name='towergamelevel',
            name='roulette_three',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,\u6982\u7387;...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=32, verbose_name='3\u661f\u5929\u8d4b'),
        ),
        migrations.AlterField(
            model_name='towergamelevel',
            name='sale_goods',
            field=models.CharField(blank=True, help_text='\u666e\u901a\u5546\u54c1ID,\u9ad8\u7ea7\u5546\u54c1ID,\u6982\u7387;...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=255, verbose_name='\u6298\u6263\u5546\u54c1'),
        ),
    ]
