# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0004_auto_20160429_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towergamelevel',
            old_name='npc_path',
            new_name='staffs',
        ),
        migrations.RenameField(
            model_name='towergamelevel',
            old_name='buff',
            new_name='talent_id',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='roulette_nine',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='roulette_six',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='roulette_three',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='star_one',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='star_three',
        ),
        migrations.RemoveField(
            model_name='towergamelevel',
            name='star_two',
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='star_reward_1',
            field=models.CharField(blank=True, help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='1\u661f\u5956\u52b1'),
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='star_reward_2',
            field=models.CharField(blank=True, help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='2\u661f\u5956\u52b1'),
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='star_reward_3',
            field=models.CharField(blank=True, help_text='\u7269\u54c1ID,\u6570\u91cf;\u7269\u54c1ID,\u6570\u91cf...', max_length=255, verbose_name='3\u661f\u5956\u52b1'),
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='turntable_3',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=255, verbose_name='3\u661f\u5929\u8d4b'),
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='turntable_6',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=255, verbose_name='6\u661f\u5929\u8d4b'),
        ),
        migrations.AddField(
            model_name='towergamelevel',
            name='turntable_9',
            field=models.CharField(blank=True, help_text='\u5929\u8d4bID,...(\u6ca1\u6709\u5219\u4e0d\u586b)', max_length=255, verbose_name='9\u661f\u5929\u8d4b'),
        ),
    ]
