# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0005_auto_20160504_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towerresetcost',
            name='times',
        ),
        migrations.AlterField(
            model_name='towerresetcost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
