# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 01:50
from __future__ import unicode_literals

from django.db import migrations

def adjust_1(apps, schema_editor):
    TowerStarReward = apps.get_model("training_tower", "TowerStarReward")

    # 先要变ID
    star_reward = TowerStarReward.objects.all()
    amount = star_reward.count()
    int_list = [-1-x for x in range(amount)]

    for i in range(amount):
        star_reward[i].id = int_list[i]
        star_reward[i].save()


    TowerRankReward = apps.get_model("training_tower", "TowerRankReward")

    rank_reward = TowerRankReward.objects.all()
    amount = rank_reward.count()
    int_list = [-1 - x for x in range(amount)]

    for i in range(amount):
        rank_reward[i].id = int_list[i]
        rank_reward[i].save()


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0007_auto_20160602_1812'),
    ]

    operations = [
        migrations.RunPython(adjust_1),
    ]
