# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0010_auto_20160603_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='towerrankreward',
            options={'verbose_name': '\u6392\u540d\u5956\u52b1', 'verbose_name_plural': '\u6392\u540d\u5956\u52b1'},
        ),
        migrations.RemoveField(
            model_name='towerrankreward',
            name='rank_cap',
        ),
        migrations.RemoveField(
            model_name='towerrankreward',
            name='rank_floor',
        ),
        migrations.RemoveField(
            model_name='towerstarreward',
            name='star',
        ),
        migrations.AlterField(
            model_name='towerrankreward',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='\u6392\u540d\u4e0a\u9650'),
        ),
        migrations.AlterField(
            model_name='towerstarreward',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
