# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 02:32
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import F


def adjust_2(apps, schema_editor):
    TowerStarReward = apps.get_model("training_tower", "TowerStarReward")
    TowerStarReward.objects.all().update(id=F('star'))

    TowerRankReward = apps.get_model("training_tower", "TowerRankReward")
    TowerRankReward.objects.all().update(id=F('rank_cap'))



class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0008_auto_20160603_0950'),
    ]

    operations = [
        migrations.RunPython(adjust_2)
    ]
