# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0009_auto_20160603_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerrankreward',
            name='rank_des',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
