# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0010_towerrankreward_rank_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='towersalegoods',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='towersalegoods',
            old_name='price',
            new_name='price_original',
        ),
        migrations.RemoveField(
            model_name='towersalegoods',
            name='num',
        ),
        migrations.RemoveField(
            model_name='towersalegoods',
            name='sale',
        ),
        migrations.AddField(
            model_name='towersalegoods',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='\u6570\u91cf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='towersalegoods',
            name='price_now',
            field=models.IntegerField(default=1, verbose_name='\u4fc3\u9500\u4ef7'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='towersalegoods',
            name='des',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='towersalegoods',
            name='vip_need',
            field=models.IntegerField(default=0, verbose_name='\u6240\u9700vip\u7b49\u7ea7'),
        ),
    ]
