# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_tower', '0012_auto_20160607_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towersalegoods',
            name='tp',
        ),
        migrations.RemoveField(
            model_name='towersalegoods',
            name='tp_icon',
        ),
    ]
