# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welfare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welfarelevelreward',
            name='level',
        ),
        migrations.RemoveField(
            model_name='welfarenewplayer',
            name='day',
        ),
    ]
