# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_clublevel_max_staff_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TibuSlot',
        ),
    ]
