# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_delete_tibuslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clublevel',
            name='max_staff_amount',
        ),
        migrations.RemoveField(
            model_name='clublevel',
            name='renown',
        ),
        migrations.AddField(
            model_name='clublevel',
            name='exp',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x8d\x87\xe5\x88\xb0\xe6\x89\x80\xe9\x9c\x80\xe7\xbb\x8f\xe9\xaa\x8c'),
            preserve_default=False,
        ),
    ]
