# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_auto_20160422_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='clublevel',
            name='des',
            field=models.TextField(blank=True),
        ),
    ]
