# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_clublevel_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='clublevel',
            name='energy',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xa2\x9e\xe9\x95\xbf\xe4\xbd\x93\xe5\x8a\x9b'),
        ),
    ]
