# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('club_level', models.IntegerField()),
                ('des', models.TextField()),
            ],
            options={
                'db_table': 'formation_slot',
                'verbose_name': '\u9635\u578b\u683c\u5b50',
                'verbose_name_plural': '\u9635\u578b\u683c\u5b50',
            },
        ),
    ]
