# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('tp', models.IntegerField(choices=[(0, '\u901a\u7528'), (1, '\u4eba'), (2, '\u795e'), (3, '\u866b')])),
                ('active_need_star', models.IntegerField()),
                ('active_need_items', models.CharField(help_text='id,amount;id,amount...', max_length=255)),
                ('use_condition', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'formation',
                'verbose_name': '\u9635\u578b',
                'verbose_name_plural': '\u9635\u578b',
            },
        ),
        migrations.CreateModel(
            name='FormationLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('formation_id', models.IntegerField(db_index=True)),
                ('level', models.IntegerField()),
                ('level_up_need_star', models.IntegerField()),
                ('talent_effects', models.CharField(max_length=255)),
                ('side_attack_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'formation_level',
                'verbose_name': '\u9635\u578b\u7b49\u7ea7',
                'verbose_name_plural': '\u9635\u578b\u7b49\u7ea7',
            },
        ),
    ]
