# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-01 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0003_formationlevel_level_up_need_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='club_level',
            new_name='challenge_id',
        ),
    ]
