# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u526f\u672cID')),
                ('name', models.CharField(max_length=32, verbose_name='\u526f\u672c\u540d\u79f0')),
                ('cost', models.IntegerField(verbose_name='\u6d88\u8017\u4f53\u529b')),
                ('open_time', models.CharField(max_length=32, verbose_name='\u5f00\u542f\u65f6\u95f4')),
                ('des', models.TextField(verbose_name='\u526f\u672c\u7b80\u4ecb')),
            ],
            options={
                'db_table': 'dungeon',
                'verbose_name': '\u526f\u672c',
                'verbose_name_plural': '\u526f\u672c',
            },
        ),
        migrations.CreateModel(
            name='DungeonGrade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u526f\u672c\u7b49\u7ea7ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u526f\u672c\u7b49\u7ea7\u540d')),
                ('grade', models.IntegerField(verbose_name='\u526f\u672c\u7b49\u7ea7')),
                ('belong', models.IntegerField(verbose_name='\u526f\u672c\u6240\u5c5e')),
                ('power', models.IntegerField(verbose_name='\u53c2\u8003\u6218\u529b')),
                ('need_level', models.IntegerField(verbose_name='\u7b49\u7ea7\u9650\u5236')),
                ('drop', models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387;\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387;', max_length=255, verbose_name='\u6389\u843d\u914d\u7f6e')),
                ('npc_path', models.CharField(help_text='\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID;\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID;', max_length=255, verbose_name='\u602a\u7269\u914d\u7f6e')),
                ('des', models.TextField(verbose_name='\u526f\u672c\u7b49\u7ea7\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'dungeon_grade',
                'verbose_name': '\u526f\u672c\u7b49\u7ea7',
                'verbose_name_plural': '\u526f\u672c\u7b49\u7ea7',
            },
        ),
    ]
