# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeongrade',
            name='grade',
        ),
        migrations.AlterField(
            model_name='dungeon',
            name='open_time',
            field=models.CharField(help_text='1,3,5 -- \u5468\u4e00\u3001\u4e09\u3001\u4e94\u5f00\u542f', max_length=32, verbose_name='\u5f00\u542f\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='dungeongrade',
            name='drop',
            field=models.CharField(help_text='\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387;\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387', max_length=255, verbose_name='\u6389\u843d\u914d\u7f6e'),
        ),
        migrations.AlterField(
            model_name='dungeongrade',
            name='npc_path',
            field=models.CharField(help_text='\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID;\u4f4d\u7f6e,\u9009\u624bID,\u5175\u79cdID', max_length=255, verbose_name='\u602a\u7269\u914d\u7f6e'),
        ),
    ]
