# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0002_auto_20160426_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='open_des',
            field=models.TextField(default='', verbose_name='\u5f00\u542f\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
