# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0003_dungeon_open_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='icon',
            field=models.CharField(default='', max_length=32, verbose_name='ICON'),
            preserve_default=False,
        ),
    ]
