# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0004_dungeon_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dungeongrade',
            name='npc_path',
        ),
        migrations.AddField(
            model_name='dungeongrade',
            name='npc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dungeongrade',
            name='drop',
            field=models.TextField(help_text='\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387;\u7269\u54c1ID,\u6570\u91cf,\u6389\u843d\u51e0\u7387', max_length=255, verbose_name='\u6389\u843d\u914d\u7f6e'),
        ),
    ]
