# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0008_dungeonresetcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='map_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
