# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dungeon', '0009_dungeon_map_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeongrade',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
