# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionshipBet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('round_num', models.IntegerField(choices=[(16, '16 \u8fdb 8'), (8, '8 \u8fdb 4'), (4, '4 \u8fdb 2'), (2, '2 \u8fdb 1')])),
                ('cost', models.TextField()),
                ('win_mail_title', models.CharField(max_length=255)),
                ('win_mail_content', models.TextField()),
                ('win_reward', models.TextField()),
                ('lose_mail_title', models.CharField(max_length=255)),
                ('lose_mail_content', models.TextField()),
                ('lose_reward', models.TextField()),
            ],
            options={
                'db_table': 'championship_bet',
                'verbose_name': '\u4e0b\u6ce8',
                'verbose_name_plural': '\u4e0b\u6ce8',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipRankReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.TextField()),
                ('reward', models.TextField()),
            ],
            options={
                'db_table': 'championship_rank_reward',
                'verbose_name': '\u5c0f\u7ec4\u6392\u540d\u5956\u52b1',
                'verbose_name_plural': '\u5c0f\u7ec4\u6392\u540d\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipScoreReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.TextField()),
                ('reward', models.TextField()),
            ],
            options={
                'db_table': 'championship_score_reward',
                'verbose_name': '\u5c0f\u7ec4\u5206\u6570\u5956\u52b1',
                'verbose_name_plural': '\u5c0f\u7ec4\u5206\u6570\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='ChampionshipWinScore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
            options={
                'db_table': 'championship_winscore',
                'verbose_name': '\u83b7\u53d6\u5206\u6570',
                'verbose_name_plural': '\u83b7\u53d6\u5206\u6570',
            },
        ),
    ]
