# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bet',
            new_name='ChampionshipBet',
        ),
        migrations.RenameModel(
            old_name='ScoreReward',
            new_name='ChampionshipRankReward',
        ),
        migrations.RenameModel(
            old_name='RankReward',
            new_name='ChampionshipScoreReward',
        ),
        migrations.RenameModel(
            old_name='WinScore',
            new_name='ChampionshipWinScore',
        ),
        migrations.AlterModelOptions(
            name='championshiprankreward',
            options={'verbose_name': '\u5c0f\u7ec4\u6392\u540d\u5956\u52b1', 'verbose_name_plural': '\u5c0f\u7ec4\u6392\u540d\u5956\u52b1'},
        ),
        migrations.AlterModelOptions(
            name='championshipscorereward',
            options={'verbose_name': '\u5c0f\u7ec4\u5206\u6570\u5956\u52b1', 'verbose_name_plural': '\u5c0f\u7ec4\u5206\u6570\u5956\u52b1'},
        ),
        migrations.AlterModelTable(
            name='championshiprankreward',
            table='championship_rank_reward',
        ),
        migrations.AlterModelTable(
            name='championshipscorereward',
            table='championship_score_reward',
        ),
    ]
