# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 07:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championshiprankreward',
            options={'verbose_name': '\u6392\u540d\u5956\u52b1', 'verbose_name_plural': '\u6392\u540d\u5956\u52b1'},
        ),
    ]
