# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-16 03:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championship', '0002_auto_20161215_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='championshipbet',
            old_name='round_num',
            new_name='level',
        ),
    ]
