# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qianban', '0007_qianban_story_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qianban',
            name='addition_tp',
        ),
        migrations.RemoveField(
            model_name='qianban',
            name='addition_value',
        ),
        migrations.AddField(
            model_name='qianban',
            name='staff_oid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qianban',
            name='talent_effect_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qianban',
            name='condition_tp',
            field=models.IntegerField(choices=[(1, b'\xe8\xa3\x85\xe9\x85\x8d\xe5\x85\xb5\xe7\xa7\x8d')], verbose_name=b'\xe6\x9d\xa1\xe4\xbb\xb6'),
        ),
    ]
