# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qianban', '0008_auto_20160617_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qianban',
            name='name',
            field=models.CharField(max_length=32, verbose_name=b'\xe5\x90\x8d\xe5\xad\x97'),
        ),
    ]
