# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-28 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qianban', '0009_auto_20160617_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspire',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\xad\x94\xe4\xbd\x8dID')),
                ('challenge_id', models.IntegerField(verbose_name=b'\xe5\xbc\x80\xe5\x90\xaf\xe9\x9c\x80\xe8\xa6\x81\xe9\x80\x9a\xe8\xbf\x87\xe5\x85\xb3\xe5\x8d\xa1')),
                ('des', models.TextField()),
            ],
            options={
                'db_table': 'inspire',
                'verbose_name': '\u52a9\u5a01',
                'verbose_name_plural': '\u52a9\u5a01',
            },
        ),
        migrations.CreateModel(
            name='InspireLevelAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField()),
                ('level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('attack_percent', models.FloatField()),
                ('defense', models.IntegerField()),
                ('defense_percent', models.FloatField()),
                ('manage', models.IntegerField()),
                ('manage_percent', models.FloatField()),
                ('operation', models.IntegerField()),
                ('operation_percent', models.FloatField()),
            ],
            options={
                'db_table': 'inspire_level_addition',
                'verbose_name': '\u52a9\u5a01\u7b49\u7ea7\u52a0\u6210',
                'verbose_name_plural': '\u52a9\u5a01\u7b49\u7ea7\u52a0\u6210',
            },
        ),
        migrations.CreateModel(
            name='InspireStepAddition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField()),
                ('step', models.IntegerField()),
                ('attack_percent', models.FloatField(verbose_name=b'\xe6\x94\xbb\xe5\x87\xbb\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('defense_percent', models.FloatField(verbose_name=b'\xe9\x98\xb2\xe5\xbe\xa1\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('hp_percent', models.FloatField(verbose_name=b'\xe7\x94\x9f\xe5\x91\xbd\xe7\x99\xbe\xe5\x88\x86\xe6\xaf\x94')),
                ('hit_rate', models.FloatField(verbose_name=b'\xe5\x91\xbd\xe4\xb8\xad\xe7\x8e\x87')),
                ('dodge_rate', models.FloatField(verbose_name=b'\xe9\x97\xaa\xe9\x81\xbf\xe7\x8e\x87')),
                ('crit_rate', models.FloatField(verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe7\x8e\x87')),
                ('toughness_rate', models.FloatField(verbose_name=b'\xe9\x9f\xa7\xe6\x80\xa7')),
                ('crit_multiple', models.FloatField(verbose_name=b'\xe6\x9a\xb4\xe5\x87\xbb\xe8\xa2\xab\xe7\x8e\x87')),
                ('hurt_addition_to_terran', models.FloatField(verbose_name=b'\xe5\xaf\xb9\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_protoss', models.FloatField(verbose_name=b'\xe5\xaf\xb9\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_to_zerg', models.FloatField(verbose_name=b'\xe5\xaf\xb9\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_terran', models.FloatField(verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe4\xba\xba\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_protoss', models.FloatField(verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe7\xa5\x9e\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
                ('hurt_addition_by_zerg', models.FloatField(verbose_name=b'\xe5\x8f\x97\xe5\x88\xb0\xe8\x99\xab\xe6\x97\x8f\xe4\xbc\xa4\xe5\xae\xb3\xe5\x8a\xa0\xe6\x88\x90')),
            ],
            options={
                'db_table': 'inspire_step_addition',
                'verbose_name': '\u52a9\u5a01\u7b49\u9636\u52a0\u6210',
                'verbose_name_plural': '\u52a9\u5a01\u7b49\u9636\u52a0\u6210',
            },
        ),
        migrations.AlterField(
            model_name='qianban',
            name='condition_tp',
            field=models.IntegerField(choices=[(1, b'\xe8\xa3\x85\xe9\x85\x8d\xe5\x85\xb5\xe7\xa7\x8d'), (2, b'\xe9\x80\x89\xe6\x89\x8b\xe5\x90\x8c\xe6\x97\xb6\xe4\xb8\x8a\xe9\x98\xb5')], verbose_name=b'\xe6\x9d\xa1\xe4\xbb\xb6'),
        ),
    ]
