# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
            ],
            options={
                'db_table': 'energy_buy_cost',
                'verbose_name': '\u4f53\u529b\u8d2d\u4e70\u82b1\u8d39',
                'verbose_name_plural': '\u4f53\u529b\u8d2d\u4e70\u82b1\u8d39',
            },
        ),
    ]
