# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnionLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contribution', models.IntegerField()),
                ('members_limit', models.IntegerField()),
            ],
            options={
                'db_table': 'union_level',
                'verbose_name': '\u516c\u4f1a\u7b49\u7ea7',
                'verbose_name_plural': '\u516c\u4f1a\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='UnionSignIn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('contribution', models.IntegerField()),
                ('rewards', models.CharField(max_length=255)),
                ('cost', models.CharField(max_length=255)),
                ('vip', models.IntegerField()),
            ],
            options={
                'db_table': 'union_singin',
                'verbose_name': '\u516c\u4f1a\u7b7e\u5230',
                'verbose_name_plural': '\u516c\u4f1a\u7b7e\u5230',
            },
        ),
    ]
