# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionExplore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('staffs', models.CharField(max_length=255)),
                ('explore_reward', models.TextField()),
                ('harass_reward', models.TextField()),
            ],
            options={
                'db_table': 'union_explore',
                'verbose_name': '\u516c\u4f1a\u63a2\u7d22/\u9a9a\u6270',
                'verbose_name_plural': '\u516c\u4f1a\u63a2\u7d22/\u9a9a\u6270',
            },
        ),
        migrations.CreateModel(
            name='UnionExploreRankReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank_des', models.CharField(max_length=255)),
                ('reward', models.TextField()),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.TextField()),
            ],
            options={
                'db_table': 'union_explore_rank_reward',
                'verbose_name': '\u516c\u4f1a\u63a2\u7d22\u5ea6\u6392\u540d\u5956\u52b1',
                'verbose_name_plural': '\u516c\u4f1a\u63a2\u7d22\u5ea6\u6392\u540d\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='UnionMemberExploreRankReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank_des', models.CharField(max_length=255)),
                ('reward', models.TextField()),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.TextField()),
            ],
            options={
                'db_table': 'union_member_explore_rank_reward',
                'verbose_name': '\u4e2a\u4eba\u63a2\u7d22\u5ea6\u6392\u540d\u5956\u52b1',
                'verbose_name_plural': '\u4e2a\u4eba\u63a2\u7d22\u5ea6\u6392\u540d\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='UnionSkill',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('skill_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('level_up_cost', models.TextField()),
                ('talent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'union_skill',
                'verbose_name': '\u516c\u4f1a\u6280\u80fd',
                'verbose_name_plural': '\u516c\u4f1a\u6280\u80fd',
            },
        ),
    ]
