# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0003_auto_20170109_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionHarassBuyTimesCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u8d2d\u4e70\u6b21\u6570')),
                ('diamond', models.IntegerField()),
            ],
            options={
                'db_table': 'union_harass_buy_times_cost',
                'verbose_name': '\u9a9a\u6270\u8d2d\u4e70\u6b21\u6570\u6d88\u8d39',
                'verbose_name_plural': '\u9a9a\u6270\u8d2d\u4e70\u6b21\u6570\u6d88\u8d39',
            },
        ),
    ]
