# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('union', '0004_unionharassbuytimescost'),
    ]

    operations = [
        migrations.AddField(
            model_name='unionskill',
            name='icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
