# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u5929\u8d4bID')),
                ('tp', models.IntegerField(choices=[(1, '\u4eba\u65cf\u5929\u8d4b'), (2, '\u866b\u65cf\u5929\u8d4b'), (3, '\u795e\u65cf\u5929\u8d4b')], verbose_name='\u5929\u8d4b\u7c7b\u578b')),
                ('name', models.CharField(max_length=32, verbose_name='\u5929\u8d4b\u540d')),
                ('position', models.IntegerField(verbose_name='\u5929\u8d4b\u4f4d\u7f6e')),
                ('unlock', models.IntegerField(verbose_name='\u89e3\u9501\u6761\u4ef6')),
                ('up_need', models.CharField(max_length=32, verbose_name='\u6d88\u8017\u9053\u5177')),
                ('image', models.CharField(max_length=255, verbose_name='\u5929\u8d4b\u56fe\u7247')),
                ('des', models.CharField(max_length=255, verbose_name='\u5929\u8d4b\u63cf\u8ff0')),
            ],
            options={
                'db_table': 'talent',
                'verbose_name': '\u5929\u8d4b',
                'verbose_name_plural': '\u5929\u8d4b',
            },
        ),
    ]
