# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0014_talentskill'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='effect_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.TalentSkill', verbose_name='\u5929\u8d4b\u6548\u679c'),
        ),
    ]
