# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talent_effect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='des',
            field=models.TextField(verbose_name='\u5929\u8d4b\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='unlock',
            field=models.IntegerField(verbose_name='\u524d\u7f6e\u6761\u4ef6'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='up_need',
            field=models.CharField(help_text='id,amounts;ld,amounts', max_length=32, verbose_name='\u6d88\u8017\u9053\u5177'),
        ),
    ]
