# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_auto_20160414_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='effect_id',
            field=models.IntegerField(default=0, verbose_name='\u5929\u8d4b\u6548\u679c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talent',
            name='tp',
            field=models.IntegerField(choices=[(1, '\u4eba\u65cf\u5929\u8d4b'), (2, '\u795e\u65cf\u5929\u8d4b'), (3, '\u866b\u65cf\u5929\u8d4b')], verbose_name='\u5929\u8d4b\u7c7b\u578b'),
        ),
    ]
