# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_auto_20160414_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='next_id',
            field=models.IntegerField(default=0, verbose_name=b'\xe4\xb8\x8b\xe4\xb8\x80\xe4\xb8\xaa\xe7\xba\xa7\xe5\xa4\xa9\xe8\xb5\x8bID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talent',
            name='des',
            field=models.TextField(verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe6\x8f\x8f\xe8\xbf\xb0'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='effect_id',
            field=models.IntegerField(verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe6\x95\x88\xe6\x9e\x9c'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8bID'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='image',
            field=models.CharField(max_length=255, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe5\x9b\xbe\xe7\x89\x87'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(max_length=32, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe5\x90\x8d'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='position',
            field=models.IntegerField(verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe4\xbd\x8d\xe7\xbd\xae'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe4\xba\xba\xe6\x97\x8f\xe5\xa4\xa9\xe8\xb5\x8b'), (2, b'\xe7\xa5\x9e\xe6\x97\x8f\xe5\xa4\xa9\xe8\xb5\x8b'), (3, b'\xe8\x99\xab\xe6\x97\x8f\xe5\xa4\xa9\xe8\xb5\x8b')], verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='unlock',
            field=models.IntegerField(verbose_name=b'\xe5\x89\x8d\xe7\xbd\xae\xe6\x9d\xa1\xe4\xbb\xb6'),
        ),
        migrations.AlterField(
            model_name='talent',
            name='up_need',
            field=models.CharField(help_text=b'id,amounts;ld,amounts', max_length=32, verbose_name=b'\xe6\xb6\x88\xe8\x80\x97\xe9\x81\x93\xe5\x85\xb7'),
        ),
    ]
