# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_auto_20160415_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='effect_lv',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\xa4\xa9\xe8\xb5\x8b\xe7\xad\x89\xe7\xba\xa7'),
            preserve_default=False,
        ),
    ]
