# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0006_talent_effect_lv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talent',
            name='effect_lv',
        ),
    ]
