# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0007_remove_talent_effect_lv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='up_need',
            field=models.IntegerField(verbose_name=b'\xe6\xb6\x88\xe8\x80\x97\xe5\xa4\xa9\xe8\xb5\x8b\xe7\x82\xb9\xe6\x95\xb0'),
        ),
    ]
