# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_auto_20160415_1801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talent',
            options={'verbose_name': '\u5929\u8d4b\u6811', 'verbose_name_plural': '\u5929\u8d4b\u6811'},
        ),
        migrations.AlterField(
            model_name='talent',
            name='up_need',
            field=models.CharField(help_text=b'ID,Number;ID,Number...', max_length=255, verbose_name=b'\xe6\xb6\x88\xe8\x80\x97\xe5\xa4\xa9\xe8\xb5\x8b\xe7\x82\xb9\xe6\x95\xb0'),
        ),
    ]
