# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_auto_20160418_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talent',
            name='unlock',
            field=models.CharField(help_text=b'ID,ID,ID...', max_length=255, verbose_name=b'\xe5\x89\x8d\xe7\xbd\xae\xe6\x9d\xa1\xe4\xbb\xb6'),
        ),
    ]
