# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 04:54
from __future__ import unicode_literals

from django.db import migrations

def change_unlock(apps, schema_editor):
    Talent = apps.get_model("talent", "Talent")
    positions = Talent.objects.values_list('position', flat=True).distinct()
    positions = list(positions)

    for tp in [1, 2, 3]:
        for pos in positions:
            ids = Talent.objects.filter(tp=tp).filter(position=pos).order_by('id').values_list('id', flat=True)
            ids = list(ids)

            if ids:
                ids.pop(0)
                Talent.objects.filter(id__in=ids).update(unlock=-1)


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0014_auto_20160601_1239'),
    ]

    operations = [
        migrations.RunPython(change_unlock)
    ]
