# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0010_skillwashcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skilllevel',
            name='upgrade_training_amount',
        ),
        migrations.RemoveField(
            model_name='skilllevel',
            name='upgrade_training_id',
        ),
        migrations.AddField(
            model_name='skilllevel',
            name='upgrade_items',
            field=models.CharField(blank=True, max_length=255, verbose_name=b'\xe5\x8d\x87\xe7\xba\xa7\xe6\x89\x80\xe9\x9c\x80\xe7\x89\xa9\xe5\x93\x81'),
        ),
    ]
