# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0011_auto_20160118_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilllevel',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name=b'\xe5\x8d\x87\xe7\xba\xa7\xe6\x89\x80\xe9\x9c\x80\xe5\x88\x86\xe9\x92\x9f'),
        ),
    ]
