# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0012_skilllevel_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buff',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField()),
                ('level', models.IntegerField()),
                ('effect', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'buff',
                'verbose_name': 'Buff',
                'verbose_name_plural': 'Buff',
            },
        ),
    ]
