# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0015_auto_20160411_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buff',
            name='value',
        ),
        migrations.AlterField(
            model_name='buff',
            name='effect',
            field=models.CharField(max_length=255),
        ),
    ]
