# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0018_auto_20160623_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='buff',
            name='stack',
            field=models.IntegerField(default=1),
        ),
    ]
