# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0019_buff_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='buff',
            name='fx',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
