# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0020_buff_fx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buff',
            name='fx',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
