# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plunder', '0003_plunderdayreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='plunderdayreward',
            name='des',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
