# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaNPC',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u6392\u540d\u4e0a\u9650')),
                ('npcs', models.CommaSeparatedIntegerField(max_length=255)),
            ],
            options={
                'db_table': 'arena_npc',
                'verbose_name': '\u7ade\u6280\u573aNPC',
                'verbose_name_plural': '\u7ade\u6280\u573aNPC',
            },
        ),
        migrations.CreateModel(
            name='BuyTimesCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u8d2d\u4e70\u6b21\u6570')),
                ('diamond', models.IntegerField()),
            ],
            options={
                'db_table': 'arena_buy_times_cost',
                'verbose_name': '\u8d2d\u4e70\u6b21\u6570\u6d88\u8d39',
                'verbose_name_plural': '\u8d2d\u4e70\u6b21\u6570\u6d88\u8d39',
            },
        ),
        migrations.CreateModel(
            name='HonorReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u8363\u8000\u70b9')),
                ('reward', models.CharField(help_text='id,amount;id,amount', max_length=255)),
            ],
            options={
                'db_table': 'arena_honor_reward',
                'verbose_name': '\u8363\u8000\u79ef\u5206\u5956\u52b1',
                'verbose_name_plural': '\u8363\u8000\u79ef\u5206\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='MatchReward',
            fields=[
                ('id', models.IntegerField(choices=[(1, '\u80dc\u5229'), (2, '\u5931\u8d25')], primary_key=True, serialize=False)),
                ('honor', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_amount', models.IntegerField()),
                ('random_items', models.TextField(help_text='id,amount,prob;')),
            ],
            options={
                'db_table': 'arena_match_reward',
                'verbose_name': '\u6bd4\u8d5b\u5956\u52b1',
                'verbose_name_plural': '\u6bd4\u8d5b\u5956\u52b1',
            },
        ),
        migrations.CreateModel(
            name='RankReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u6392\u540d\u4e0a\u9650')),
                ('reward', models.CharField(help_text='id,amount;id,amount', max_length=255)),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'arena_rank_reward',
                'verbose_name': '\u6392\u540d\u5956\u52b1',
                'verbose_name_plural': '\u6392\u540d\u5956\u52b1',
            },
        ),
    ]
