# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchreward',
            name='random_items',
            field=models.TextField(blank=True, help_text='id,amount,prob;'),
        ),
    ]
