# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0002_auto_20160428_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLogTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('template', models.TextField()),
            ],
            options={
                'db_table': 'arena_match_log_template',
                'verbose_name': '\u6218\u62a5\u6a21\u677f',
                'verbose_name_plural': '\u6218\u62a5\u6a21\u677f',
            },
        ),
    ]
