# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0003_matchlogtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='honorreward',
            name='des',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
