# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0004_honorreward_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankreward',
            name='rank_des',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
