# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0005_rankreward_rank_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRange',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u6392\u540d\u4e0a\u9650')),
                ('range_1', models.IntegerField()),
                ('range_2', models.IntegerField()),
                ('range_3', models.IntegerField()),
                ('range_4', models.IntegerField()),
            ],
            options={
                'db_table': 'arena_search_range',
                'verbose_name': '\u5bf9\u624b\u641c\u7d22\u8303\u56f4',
                'verbose_name_plural': '\u5bf9\u624b\u641c\u7d22\u8303\u56f4',
            },
        ),
    ]
