# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0006_searchrange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('diamond', models.IntegerField()),
            ],
            options={
                'db_table': 'arena_reset_cost',
                'verbose_name': '\u91cd\u7f6e\u82b1\u8d39',
                'verbose_name_plural': '\u91cd\u7f6e\u82b1\u8d39',
            },
        ),
        migrations.RemoveField(
            model_name='searchrange',
            name='range_3',
        ),
        migrations.RemoveField(
            model_name='searchrange',
            name='range_4',
        ),
        migrations.AddField(
            model_name='arenanpc',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arenanpc',
            name='score_high',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='arenanpc',
            name='score_low',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='searchrange',
            name='score_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchrange',
            name='score_win',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='arenanpc',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchrange',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
