# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-12 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0007_auto_20160712_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrange',
            name='range_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='searchrange',
            name='range_2',
            field=models.FloatField(),
        ),
    ]
