# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0008_auto_20160712_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankRewardWeekly',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='\u6392\u540d\u4e0a\u9650')),
                ('rank_des', models.CharField(blank=True, max_length=255)),
                ('reward', models.CharField(help_text='id,amount;id,amount', max_length=255)),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'arena_rank_reward_weekly',
                'verbose_name': '\u6392\u540d\u5956\u52b1 - \u5468',
                'verbose_name_plural': '\u6392\u540d\u5956\u52b1 - \u5468',
            },
        ),
        migrations.AlterModelOptions(
            name='rankreward',
            options={'verbose_name': '\u6392\u540d\u5956\u52b1 - \u65e5', 'verbose_name_plural': '\u6392\u540d\u5956\u52b1 - \u65e5'},
        ),
    ]
