# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0007_auto_20151222_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='training_skill',
        ),
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='training_skill_amount',
        ),
        migrations.AlterField(
            model_name='ladderscorestore',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.Item', verbose_name=b'\xe7\x89\xa9\xe5\x93\x81'),
        ),
        migrations.AlterField(
            model_name='ladderscorestore',
            name='item_amount',
            field=models.IntegerField(default=1, verbose_name=b'\xe7\x89\xa9\xe5\x93\x81\xe6\x95\xb0\xe9\x87\x8f'),
        ),
    ]
