# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0008_auto_20160107_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='des',
        ),
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='name',
        ),
    ]
