# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0009_auto_20160129_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ladderscorestore',
            name='item',
        ),
    ]
