# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vip',
            old_name='update_vip_exp',
            new_name='exp',
        ),
        migrations.AddField(
            model_name='vip',
            name='arena_buy_times',
            field=models.IntegerField(default=0, verbose_name='\u7ade\u6280\u573a\u8d2d\u4e70\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='vip',
            name='challenge_reset_times',
            field=models.IntegerField(default=0, verbose_name='\u4e3b\u7ebf\u526f\u672c\u6bcf\u65e5\u91cd\u7f6e\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='vip',
            name='daily_dungeon_reset_times',
            field=models.IntegerField(default=0, verbose_name='\u65e5\u5e38\u526f\u672c\u91cd\u7f6e\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='vip',
            name='tower_reset_times',
            field=models.IntegerField(default=0, verbose_name='\u6311\u6218\u5854\u91cd\u7f6e\u6b21\u6570'),
        ),
    ]
