# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0002_auto_20160524_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='energy_buy_times',
            field=models.IntegerField(default=0, verbose_name='\u4f53\u529b\u8d2d\u4e70\u6b21\u6570'),
        ),
    ]
