# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0003_vip_energy_buy_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='store_refresh_times',
            field=models.IntegerField(default=5, verbose_name='\u795e\u79d8\u5546\u5e97\u5237\u65b0\u6b21\u6570'),
        ),
    ]
