# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0004_vip_store_refresh_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='territory_help_times',
            field=models.IntegerField(default=0, verbose_name='\u9886\u5730\u5e2e\u52a9\u597d\u53cb\u6b21\u6570'),
        ),
    ]
