# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0005_vip_territory_help_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='arena_search_reset_times',
            field=models.IntegerField(default=5, verbose_name='\u7ade\u6280\u573a\u641c\u7d22\u91cd\u7f6e\u6b21\u6570'),
        ),
    ]
