# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0006_vip_arena_search_reset_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='vip',
            name='plunder_times',
            field=models.IntegerField(default=10, verbose_name='\u63a0\u593a\u6b21\u6570'),
        ),
    ]
