# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0007_vip_plunder_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vip',
            name='plunder_times',
        ),
        migrations.AddField(
            model_name='vip',
            name='plunder_buy_times',
            field=models.IntegerField(default=10, verbose_name='\u63a0\u593a\u8d2d\u4e70\u6b21\u6570'),
        ),
    ]
