# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0015_auto_20151230_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='trainings',
        ),
        migrations.AddField(
            model_name='package',
            name='staff_cards',
            field=models.CharField(blank=True, help_text=b'id:\xe6\x95\xb0\xe9\x87\x8f,id:\xe6\x95\xb0\xe9\x87\x8f', max_length=255, verbose_name=b'\xe5\x91\x98\xe5\xb7\xa5\xe5\x8d\xa1'),
        ),
        migrations.AlterField(
            model_name='package',
            name='items',
            field=models.CharField(blank=True, help_text=b'id:\xe6\x95\xb0\xe9\x87\x8f,id:\xe6\x95\xb0\xe9\x87\x8f', max_length=255, verbose_name=b'\xe7\x89\xa9\xe5\x93\x81'),
        ),
    ]
