# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0017_auto_20160107_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='staffs',
        ),
    ]
