# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-09 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_npc', '0002_auto_20151106_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientnpcdialog',
            name='npc',
        ),
        migrations.DeleteModel(
            name='ClientNPC',
        ),
        migrations.DeleteModel(
            name='ClientNPCDiaLog',
        ),
    ]
