# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0006_auto_20151106_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeConversation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('challenge_id', models.IntegerField()),
                ('mode', models.IntegerField(choices=[(1, b'\xe6\x88\x98\xe5\x89\x8d'), (2, b'\xe6\x88\x98\xe5\x90\x8e')])),
                ('pos', models.IntegerField(choices=[(1, b'\xe5\xb7\xa6\xe8\xbe\xb9'), (2, b'\xe5\x8f\xb3\xe8\xbe\xb9')])),
                ('picture', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'challenge_conversation',
                'verbose_name': '\u6311\u6218\u8d5b\u5bf9\u8bdd',
                'verbose_name_plural': '\u6311\u6218\u8d5b\u5bf9\u8bdd',
            },
        ),
    ]
