# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0007_challengeconversation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengeconversation',
            old_name='content',
            new_name='dialog',
        ),
        migrations.RenameField(
            model_name='challengeconversation',
            old_name='picture',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='challengeconversation',
            old_name='pos',
            new_name='position',
        ),
    ]
