# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseGoods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField(blank=True)),
                ('rmb', models.IntegerField()),
                ('vip_exp', models.IntegerField()),
                ('diamond', models.IntegerField()),
                ('diamond_extra', models.IntegerField()),
            ],
            options={
                'db_table': 'purchase_goods',
                'verbose_name': '\u5145\u503c\u5546\u54c1',
                'verbose_name_plural': '\u5145\u503c\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='PurchaseYueka',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.TextField(blank=True)),
                ('rmb', models.IntegerField()),
                ('vip_exp', models.IntegerField()),
                ('rewards', models.CharField(max_length=255)),
                ('mail_title', models.CharField(max_length=255)),
                ('mail_content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'purchase_yueka',
                'verbose_name': '\u6708\u5361',
                'verbose_name_plural': '\u6708\u5361',
            },
        ),
    ]
