# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseFirstReward',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rewards', models.TextField()),
            ],
            options={
                'db_table': 'purchase_first_reward',
                'verbose_name': '\u9996\u5145\u5956\u52b1',
                'verbose_name_plural': '\u9996\u5145\u5956\u52b1',
            },
        ),
    ]
