# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-01 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20160812_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasegoods',
            name='ios_product_id',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseyueka',
            name='ios_product_id',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
