# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_auto_20151222_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglevels',
            name='effect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='building.BuildingEffect', verbose_name=b'\xe5\xbb\xba\xe7\xad\x91\xe6\x95\x88\xe6\x9e\x9c'),
        ),
    ]
