# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0020_auto_20151222_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingeffectinfo',
            unique_together=set([('building_effect', 'tp')]),
        ),
    ]
