# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0022_auto_20151222_1554'),
        ('building', '0025_shop_sells_per_hour'),
    ]

    operations = [
    ]
