# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0027_auto_20160125_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': '\u5efa\u7b51', 'verbose_name_plural': '\u5efa\u7b51'},
        ),
    ]
