# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0028_auto_20160125_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='condition',
        ),
    ]
