# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0029_remove_sponsor_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='condition',
            field=models.IntegerField(default=1, verbose_name=b'\xe9\x9c\x80\xe8\xa6\x81\xe9\x80\x9a\xe8\xbf\x87\xe7\x9a\x84\xe6\x8c\x91\xe6\x88\x98\xe8\xb5\x9b'),
            preserve_default=False,
        ),
    ]
