# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0030_sponsor_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessbroadcastreward',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='goods',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.DeleteModel(
            name='BusinessBroadcastReward',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
