# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0031_auto_20160411_1618'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildingeffectinfo',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='buildingeffectinfo',
            name='building_effect',
        ),
        migrations.RemoveField(
            model_name='buildinglevels',
            name='building',
        ),
        migrations.RemoveField(
            model_name='buildinglevels',
            name='effect',
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='BuildingEffect',
        ),
        migrations.DeleteModel(
            name='BuildingEffectInfo',
        ),
        migrations.DeleteModel(
            name='BuildingLevels',
        ),
    ]
