# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building', '0032_auto_20160512_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('des', models.TextField()),
                ('effect_day', models.CharField(max_length=255)),
                ('effect_night', models.CharField(max_length=255)),
                ('model_resource', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'building_new',
                'verbose_name': '\u5efa\u7b51',
                'verbose_name_plural': '\u5efa\u7b51',
            },
        ),
    ]
