# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0033_buildingnew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingnew',
            old_name='effect_day',
            new_name='day_effect',
        ),
        migrations.RenameField(
            model_name='buildingnew',
            old_name='effect_night',
            new_name='night_effect',
        ),
    ]
