# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('talent_effect_id', models.IntegerField()),
            ],
            options={
                'db_table': 'collection',
                'verbose_name': '\u6536\u96c6\u56fe\u9274',
                'verbose_name_plural': '\u6536\u96c6\u56fe\u9274',
            },
        ),
    ]
