# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0020_auto_20160106_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengematch',
            name='max_times',
            field=models.IntegerField(default=1, verbose_name=b'\xe6\xac\xa1\xe6\x95\xb0\xe9\x99\x90\xe5\x88\xb6'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='challengetype',
            name='star_reward',
            field=models.CharField(default=b'\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID,\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID,\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID', max_length=255, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe5\xa5\x96\xe5\x8a\xb1'),
        ),
        migrations.AlterField(
            model_name='elitearea',
            name='star_reward',
            field=models.CharField(default=b'\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID,\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID,\xe6\x98\x9f\xe7\xba\xa7\xe6\x95\xb0:\xe7\x89\xa9\xe5\x93\x81\xe5\x8c\x85ID', max_length=255, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe5\xa5\x96\xe5\x8a\xb1'),
        ),
    ]
