# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_auto_20160106_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengetype',
            name='star_reward',
            field=models.CharField(max_length=255, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe5\xa5\x96\xe5\x8a\xb1'),
        ),
        migrations.AlterField(
            model_name='elitearea',
            name='star_reward',
            field=models.CharField(max_length=255, verbose_name=b'\xe6\x98\x9f\xe7\xba\xa7\xe5\xa5\x96\xe5\x8a\xb1'),
        ),
    ]
