# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0022_auto_20160107_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmatchreward',
            name='additional_reward',
        ),
        migrations.AddField(
            model_name='trainingmatchreward',
            name='score',
            field=models.IntegerField(default=0, verbose_name=b'\xe8\x8e\xb7\xe5\xbe\x97\xe7\xa7\xaf\xe5\x88\x86'),
            preserve_default=False,
        ),
    ]
