# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0029_remove_sponsor_condition'),
        ('match', '0024_trainingmatchscorestore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengematch',
            name='club_flag',
        ),
        migrations.RemoveField(
            model_name='challengematch',
            name='package',
        ),
        migrations.RemoveField(
            model_name='challengematch',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='challengematch',
            name='tp',
        ),
        migrations.DeleteModel(
            name='ChallengeMatch',
        ),
        migrations.DeleteModel(
            name='ChallengeType',
        ),
    ]
