# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0025_auto_20160318_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeChapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('des', models.TextField()),
            ],
            options={
                'db_table': 'challenge_chapter',
                'verbose_name': '\u6311\u6218\u8d5b\u7ae0\u8282',
                'verbose_name_plural': '\u6311\u6218\u8d5b\u7ae0\u8282',
            },
        ),
        migrations.CreateModel(
            name='ChallengeMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField(choices=[(1, b'\xe6\x99\xae\xe9\x80\x9a'), (1, b'\xe7\xb2\xbe\xe8\x8b\xb1')], verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('area', models.CharField(max_length=255, verbose_name=b'\xe5\xa4\xa7\xe5\x8c\xba\xe5\x90\x8d')),
                ('chapter', models.IntegerField(verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82')),
                ('name', models.CharField(max_length=255, verbose_name=b'\xe5\x85\xb3\xe5\x8d\xa1\xe5\x90\x8d')),
                ('des', models.TextField(verbose_name=b'\xe6\x8f\x8f\xe8\xbf\xb0')),
                ('club_flag', models.IntegerField(verbose_name=b'\xe6\x97\x97\xe5\xb8\x9c')),
                ('energy', models.IntegerField(verbose_name=b'\xe6\xb6\x88\xe8\x80\x97\xe4\xbd\x93\xe5\x8a\x9b')),
                ('club_exp', models.IntegerField(verbose_name=b'\xe8\x8e\xb7\xe5\xbe\x97\xe4\xbf\xb1\xe4\xb9\x90\xe9\x83\xa8\xe7\xbb\x8f\xe9\xaa\x8c')),
                ('staffs', models.CharField(help_text=b'\xe4\xbd\x8d\xe7\xbd\xae\xef\xbc\x8cID\xef\xbc\x8c\xe5\x85\xb5\xe7\xa7\x8dID\xef\xbc\x9b...', max_length=255, verbose_name=b'\xe9\x80\x89\xe6\x89\x8b\xe5\x88\x97\xe8\xa1\xa8')),
                ('drop', models.CharField(help_text=b'\xe7\x89\xa9\xe5\x93\x81ID\xef\xbc\x8c\xe6\x95\xb0\xe9\x87\x8f\xef\xbc\x8c\xe5\x88\x9d\xe5\xa7\x8b\xe5\x87\xa0\xe7\x8e\x87\xef\xbc\x8c\xe9\x80\x92\xe5\xa2\x9e\xe5\x87\xa0\xe7\x8e\x87\xef\xbc\x9b...', max_length=255, verbose_name=b'\xe6\x8e\x89\xe8\x90\xbd')),
                ('condition_challenge', models.IntegerField(verbose_name=b'\xe5\x89\x8d\xe7\xbd\xae\xe5\x85\xb3\xe5\x8d\xa1ID')),
                ('times_limit', models.IntegerField(verbose_name=b'\xe6\xaf\x8f\xe6\x97\xa5\xe9\x99\x90\xe5\x88\xb6\xe6\xac\xa1\xe6\x95\xb0')),
            ],
            options={
                'db_table': 'challenge_match',
                'verbose_name': '\u6311\u6218\u8d5b',
                'verbose_name_plural': '\u6311\u6218\u8d5b',
            },
        ),
    ]
