# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0026_challengechapter_challengematch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengematch',
            name='club_flag',
            field=models.CharField(max_length=255, verbose_name=b'\xe6\x97\x97\xe5\xb8\x9c'),
        ),
    ]
