# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0028_auto_20160318_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengechapter',
            name='star_reward',
            field=models.CharField(default='a', help_text=b'\xe6\x98\x9f\xe6\x95\xb0,\xe5\xa5\x96\xe5\x8a\xb1ID,\xe5\xa5\x96\xe5\x8a\xb1\xe6\x95\xb0\xe9\x87\x8f;...', max_length=255),
            preserve_default=False,
        ),
    ]
