# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0029_challengechapter_star_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengematch',
            name='tp',
        ),
        migrations.AddField(
            model_name='challengechapter',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe6\x99\xae\xe9\x80\x9a'), (2, b'\xe7\xb2\xbe\xe8\x8b\xb1')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
            preserve_default=False,
        ),
    ]
