# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0030_auto_20160318_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengematch',
            name='area',
        ),
        migrations.AddField(
            model_name='challengechapter',
            name='area',
            field=models.CharField(default='x', max_length=255, verbose_name=b'\xe5\xa4\xa7\xe5\x8c\xba\xe5\x90\x8d'),
            preserve_default=False,
        ),
    ]
