# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0031_auto_20160318_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengematch',
            name='condition_challenge',
            field=models.IntegerField(db_index=True, verbose_name=b'\xe5\x89\x8d\xe7\xbd\xae\xe5\x85\xb3\xe5\x8d\xa1ID'),
        ),
    ]
