# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0032_auto_20160321_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EliteArea',
        ),
        migrations.RemoveField(
            model_name='elitematch',
            name='club_flag',
        ),
        migrations.RemoveField(
            model_name='elitematch',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='elitematch',
            name='reward',
        ),
        migrations.DeleteModel(
            name='MatchConversationEnd',
        ),
        migrations.DeleteModel(
            name='MatchConversationRoundEnd',
        ),
        migrations.RemoveField(
            model_name='matchconversationstart',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='matchconversationstart',
            name='race',
        ),
        migrations.RemoveField(
            model_name='trainingmatchscorestore',
            name='item',
        ),
        migrations.DeleteModel(
            name='EliteMatch',
        ),
        migrations.DeleteModel(
            name='MatchConversationStart',
        ),
    ]
