# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0033_auto_20160411_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingmatchreward',
            name='reward',
        ),
        migrations.DeleteModel(
            name='TrainingMatchScoreStore',
        ),
        migrations.DeleteModel(
            name='TrainingMatchReward',
        ),
    ]
