# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0034_auto_20160422_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeGuide',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('guide', models.IntegerField()),
                ('des', models.TextField()),
                ('return_to_main_panel', models.BooleanField()),
            ],
            options={
                'db_table': 'challenge_guide',
                'verbose_name': '\u6311\u6218\u8d5b\u5f15\u5bfc',
                'verbose_name_plural': '\u6311\u6218\u8d5b\u5f15\u5bfc',
            },
        ),
    ]
