# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0035_challengeguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeBuyCost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=b'\xe8\xb4\xad\xe4\xb9\xb0\xe6\xac\xa1\xe6\x95\xb0')),
                ('diamond', models.IntegerField(verbose_name=b'\xe9\x92\xbb\xe7\x9f\xb3')),
            ],
            options={
                'db_table': 'challenge_buy_cost',
                'verbose_name': '\u6311\u6218\u8d5b\u8d2d\u4e70\u82b1\u8d39',
                'verbose_name_plural': '\u6311\u6218\u8d5b\u8d2d\u4e70\u82b1\u8d39',
            },
        ),
    ]
