# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0038_challengematch_show_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeArea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'challenge_area',
                'verbose_name': '\u6311\u6218\u8d5b\u5927\u533a',
                'verbose_name_plural': '\u6311\u6218\u8d5b\u5927\u533a',
            },
        ),
        migrations.RemoveField(
            model_name='challengechapter',
            name='area',
        ),
    ]
