# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0040_challengechapter_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengechapter',
            name='map_name',
        ),
        migrations.AddField(
            model_name='challengematch',
            name='map_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
