# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npc', '0008_remove_npcclub_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcclub',
            name='league',
            field=models.IntegerField(default=1, verbose_name=b'\xe8\x81\x94\xe8\xb5\x9b\xe7\xad\x89\xe7\xba\xa7'),
        ),
    ]
