# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20151228_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.IntegerField(default=1, verbose_name=b'\xe5\x93\x81\xe8\xb4\xa8'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\x9f\xb9\xe8\xae\xad\xe8\x80\x97\xe6\x9d\x90'), (2, b'\xe7\xbd\x91\xe5\xba\x97\xe8\xb4\xa7\xe7\x89\xa9'), (3, b'\xe5\xbb\xba\xe7\xad\x91\xe8\xae\xb8\xe5\x8f\xaf\xe8\xaf\x81')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
