# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20160105_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('color', models.CharField(blank=True, max_length=32)),
                ('icon', models.CharField(blank=True, max_length=255)),
                ('background', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'item_quality',
                'verbose_name': '\u7269\u54c1\u54c1\u8d28',
                'verbose_name_plural': '\u7269\u54c1\u54c1\u8d28',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='quality',
        ),
    ]
