# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20160106_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item.ItemQuality', verbose_name=b'\xe5\x93\x81\xe8\xb4\xa8'),
        ),
    ]
