# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe5\x9f\xb9\xe8\xae\xad\xe8\x80\x97\xe6\x9d\x90'), (2, b'\xe7\xbd\x91\xe5\xba\x97\xe8\xb4\xa7\xe7\x89\xa9'), (3, b'\xe5\xbb\xba\xe7\xad\x91\xe8\xae\xb8\xe5\x8f\xaf\xe8\xaf\x81'), (4, b'\xe6\x8a\x80\xe8\x83\xbd\xe8\xae\xad\xe7\xbb\x83\xe4\xb9\xa6'), (11, b'\xe8\xa3\x85\xe5\xa4\x87'), (99, b'\xe7\xae\xb1\xe5\xad\x90')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
