# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20160107_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sub_tp',
            field=models.IntegerField(choices=[(0, b'\xe6\x97\xa0\xe5\xad\x90\xe7\xb1\xbb\xe5\x9e\x8b'), (1, b'\xe5\xb0\x8f\xe5\x9e\x8b\xe8\xa3\x85\xe5\xa4\x87'), (2, b'\xe5\xa4\xa7\xe5\x9e\x8b\xe8\xa3\x85\xe5\xa4\x87'), (3, b'\xe4\xba\xba\xe7\x89\xa9\xe9\x85\x8d\xe9\xa5\xb0'), (4, b'\xe4\xbf\xa1\xe7\x89\xa9'), (101, b'\xe9\xa5\xae\xe5\x93\x81'), (102, b'\xe8\xae\xad\xe7\xbb\x83\xe5\xbe\xbd\xe7\xab\xa0')], default=0, verbose_name=b'\xe5\xad\x90\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
