# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20160118_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.OneToOneField(db_column=b'id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='item.Item'),
        ),
    ]
