# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_auto_20160118_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_tp',
        ),
        migrations.AddField(
            model_name='item',
            name='group_id',
            field=models.IntegerField(default=0, verbose_name=b'\xe7\xbb\x84ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tp',
            field=models.IntegerField(choices=[(100, b'\xe9\xa5\xae\xe5\x93\x81'), (200, b'\xe5\xbe\xbd\xe7\xab\xa0'), (300, b'\xe5\xbb\xba\xe7\xad\x91\xe8\xae\xb8\xe5\x8f\xaf\xe8\xaf\x81'), (400, b'\xe7\xbd\x91\xe5\xba\x97\xe8\xb4\xa7\xe7\x89\xa9'), (500, b'\xe5\xa4\xa9\xe8\xb5\x8b\xe7\x9f\xb3'), (1000, b'\xe8\xa3\x85\xe5\xa4\x87'), (9000, b'\xe7\xae\xb1\xe5\xad\x90')], default=1, verbose_name=b'\xe7\xb1\xbb\xe5\x9e\x8b'),
        ),
    ]
