# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_auto_20160119_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='lilun',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='luoji',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='meili',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='minjie',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='wuxing',
        ),
        migrations.AddField(
            model_name='equipment',
            name='template_0',
            field=models.CharField(blank=True, help_text=b'\xe5\xb1\x9e\xe6\x80\xa7:\xe4\xb8\x8b\xe7\xba\xbf\xef\xbd\x9e\xe4\xb8\x8a\xe9\x99\x90,\xe5\xb1\x9e\xe6\x80\xa7:\xe4\xb8\x8b\xe9\x99\x90\xef\xbd\x9e\xe4\xb8\x8a\xe9\x99\x90|...', max_length=255, verbose_name=b'\xe5\x9b\xba\xe5\xae\x9a\xe6\xa8\xa1\xe6\x9d\xbf'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='template_1',
            field=models.CharField(max_length=255, verbose_name=b'\xe9\x9a\x8f\xe6\x9c\xba\xe6\xa8\xa1\xe6\x9d\xbf1'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='template_2',
            field=models.CharField(max_length=255, verbose_name=b'\xe9\x9a\x8f\xe6\x9c\xba\xe6\xa8\xa1\xe6\x9d\xbf2'),
        ),
    ]
