# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20160119_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tp', models.IntegerField(choices=[(1, b'\xe9\xbc\xa0\xe6\xa0\x87'), (2, b'\xe9\x94\xae\xe7\x9b\x98'), (3, b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x99\xa8'), (4, b'\xe9\xa5\xb0\xe5\x93\x81')])),
                ('renown', models.IntegerField(verbose_name=b'\xe5\x88\x86\xe8\xa7\xa3\xe8\x8e\xb7\xe5\xbe\x97\xe5\xa3\xb0\xe6\x9c\x9b')),
            ],
            options={
                'db_table': 'equipment_base',
                'verbose_name': '\u88c5\u5907\u57fa\u7840\u5c5e\u6027',
                'verbose_name_plural': '\u88c5\u5907\u57fa\u7840\u5c5e\u6027',
            },
        ),
        migrations.CreateModel(
            name='EquipmentLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('equip_id', models.IntegerField()),
                ('equip_level', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('attack_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('defense', models.IntegerField()),
                ('defense_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('manage', models.IntegerField()),
                ('manage_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('cost', models.IntegerField()),
                ('cost_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('update_item_need', models.CharField(max_length=255, verbose_name=b'\xe5\x8d\x87\xe7\xba\xa7\xe6\x89\x80\xe9\x9c\x80\xe9\x81\x93\xe5\x85\xb7')),
            ],
            options={
                'db_table': 'equipment_level',
                'verbose_name': '\u88c5\u5907\u7b49\u7ea7',
                'verbose_name_plural': '\u88c5\u5907\u7b49\u7ea7',
            },
        ),
        migrations.CreateModel(
            name='ItemMerge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('to_id', models.IntegerField()),
                ('renown', models.IntegerField(verbose_name=b'\xe5\x88\x86\xe8\xa7\xa3\xe8\x8e\xb7\xe5\xbe\x97\xe5\xa3\xb0\xe6\x9c\x9b')),
            ],
            options={
                'db_table': 'item_merge',
                'verbose_name': '\u788e\u7247\u5408\u6210',
                'verbose_name_plural': '\u788e\u7247\u5408\u6210',
            },
        ),
        migrations.CreateModel(
            name='ItemNew',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('des', models.TextField()),
                ('icon', models.CharField(max_length=255)),
                ('tp', models.IntegerField(choices=[(1, b'\xe6\x99\xae\xe9\x80\x9a\xe9\x81\x93\xe5\x85\xb7'), (2, b'\xe5\x8f\xaf\xe4\xbd\xbf\xe7\x94\xa8\xe9\x81\x93\xe5\x85\xb7'), (3, b'\xe4\xbb\xa3\xe5\xb8\x81\xe8\xb5\x84\xe6\xba\x90'), (4, b'\xe8\xa3\x85\xe5\xa4\x87'), (5, b'\xe7\xa2\x8e\xe7\x89\x87'), (6, b'\xe9\x80\x89\xe6\x89\x8b')])),
                ('quality', models.IntegerField()),
                ('stack_max', models.IntegerField(verbose_name=b'\xe5\xa0\x86\xe5\x8f\xa0\xe4\xb8\x8a\xe9\x99\x90')),
            ],
            options={
                'db_table': 'item_new',
                'verbose_name': '\u9053\u5177\uff08\u65b0\uff09',
                'verbose_name_plural': '\u9053\u5177\uff08\u65b0\uff09',
            },
        ),
        migrations.CreateModel(
            name='ItemUse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('use_item_id', models.IntegerField(default=0)),
                ('use_item_amount', models.IntegerField(default=0)),
                ('result', models.TextField(help_text=b'ID1,\xe6\x95\xb0\xe9\x87\x8f,\xe5\x87\xa0\xe7\x8e\x87;ID2,\xe6\x95\xb0\xe9\x87\x8f,\xe5\x87\xa0\xe7\x8e\x87|ID11,\xe6\x95\xb0\xe9\x87\x8f,\xe5\x87\xa0\xe7\x8e\x87;ID12,\xe6\x95\xb0\xe9\x87\x8f,\xe5\x87\xa0\xe7\x8e\x87|...')),
            ],
            options={
                'db_table': 'item_use',
                'verbose_name': '\u9053\u5177\u4f7f\u7528',
                'verbose_name_plural': '\u9053\u5177\u4f7f\u7528',
            },
        ),
    ]
