# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_itemmerge_crystal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentlevel',
            name='equip_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
