# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_itemexp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentlevel',
            old_name='cost',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='equipmentlevel',
            old_name='cost_percent',
            new_name='operation_percent',
        ),
    ]
