# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_delete_itemexp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemExp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'item_exp',
            },
        ),
    ]
