# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_itemexp'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemnew',
            name='sub_tp',
            field=models.IntegerField(default=0),
        ),
    ]
