# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_equipmentspecial_equipmentspecialgenerate_equipmentspecialgrowingproperty_equipmentspeciallevel_equi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentbase',
            name='tp',
            field=models.IntegerField(choices=[(1, b'\xe9\xbc\xa0\xe6\xa0\x87'), (2, b'\xe9\x94\xae\xe7\x9b\x98'), (3, b'\xe6\x98\xbe\xe7\xa4\xba\xe5\x99\xa8'), (4, b'\xe9\xa5\xb0\xe5\x93\x81'), (5, b'\xe7\x89\xb9\xe6\xae\x8a')]),
        ),
    ]
