# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_auto_20160826_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemquality',
            name='staff_icon',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
